// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: pkg/swarm/proto/swarm.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SwarmService_SpawnAgent_FullMethodName = "/swarm.SwarmService/SpawnAgent"
)

// SwarmServiceClient is the client API for SwarmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SwarmService runs on Node Agents to receive tasks.
type SwarmServiceClient interface {
	// SpawnAgent tells a node to start a new browser agent instance.
	SpawnAgent(ctx context.Context, in *SpawnAgentRequest, opts ...grpc.CallOption) (*SpawnAgentResponse, error)
}

type swarmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSwarmServiceClient(cc grpc.ClientConnInterface) SwarmServiceClient {
	return &swarmServiceClient{cc}
}

func (c *swarmServiceClient) SpawnAgent(ctx context.Context, in *SpawnAgentRequest, opts ...grpc.CallOption) (*SpawnAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpawnAgentResponse)
	err := c.cc.Invoke(ctx, SwarmService_SpawnAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SwarmServiceServer is the server API for SwarmService service.
// All implementations must embed UnimplementedSwarmServiceServer
// for forward compatibility.
//
// SwarmService runs on Node Agents to receive tasks.
type SwarmServiceServer interface {
	// SpawnAgent tells a node to start a new browser agent instance.
	SpawnAgent(context.Context, *SpawnAgentRequest) (*SpawnAgentResponse, error)
	mustEmbedUnimplementedSwarmServiceServer()
}

// UnimplementedSwarmServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSwarmServiceServer struct{}

func (UnimplementedSwarmServiceServer) SpawnAgent(context.Context, *SpawnAgentRequest) (*SpawnAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SpawnAgent not implemented")
}
func (UnimplementedSwarmServiceServer) mustEmbedUnimplementedSwarmServiceServer() {}
func (UnimplementedSwarmServiceServer) testEmbeddedByValue()                      {}

// UnsafeSwarmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SwarmServiceServer will
// result in compilation errors.
type UnsafeSwarmServiceServer interface {
	mustEmbedUnimplementedSwarmServiceServer()
}

func RegisterSwarmServiceServer(s grpc.ServiceRegistrar, srv SwarmServiceServer) {
	// If the following call panics, it indicates UnimplementedSwarmServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SwarmService_ServiceDesc, srv)
}

func _SwarmService_SpawnAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpawnAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwarmServiceServer).SpawnAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwarmService_SpawnAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwarmServiceServer).SpawnAgent(ctx, req.(*SpawnAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SwarmService_ServiceDesc is the grpc.ServiceDesc for SwarmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SwarmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swarm.SwarmService",
	HandlerType: (*SwarmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SpawnAgent",
			Handler:    _SwarmService_SpawnAgent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/swarm/proto/swarm.proto",
}

const (
	OrchestratorService_RegisterNode_FullMethodName     = "/swarm.OrchestratorService/RegisterNode"
	OrchestratorService_ReportHeartbeat_FullMethodName  = "/swarm.OrchestratorService/ReportHeartbeat"
	OrchestratorService_RequestSecret_FullMethodName    = "/swarm.OrchestratorService/RequestSecret"
	OrchestratorService_SubmitMission_FullMethodName    = "/swarm.OrchestratorService/SubmitMission"
	OrchestratorService_GetSwarmStatus_FullMethodName   = "/swarm.OrchestratorService/GetSwarmStatus"
	OrchestratorService_GetMissionResult_FullMethodName = "/swarm.OrchestratorService/GetMissionResult"
)

// OrchestratorServiceClient is the client API for OrchestratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OrchestratorService runs on the Global Orchestrator to receive node check-ins.
type OrchestratorServiceClient interface {
	// RegisterNode is called by a node when it joins the network.
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	// ReportHeartbeat is called periodically by nodes to report utilization.
	ReportHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// RequestSecret is called by nodes when they need sensitive data (e.g. login).
	// This triggers a user authorization flow on the Orchestrator host.
	RequestSecret(ctx context.Context, in *RequestSecretRequest, opts ...grpc.CallOption) (*RequestSecretResponse, error)
	// SubmitMission is called by an Initiator (e.g. Mobile) to start a new mission.
	SubmitMission(ctx context.Context, in *SubmitMissionRequest, opts ...grpc.CallOption) (*SubmitMissionResponse, error)
	// GetSwarmStatus returns the live state of all registered nodes.
	GetSwarmStatus(ctx context.Context, in *SwarmStatusRequest, opts ...grpc.CallOption) (*SwarmStatusResponse, error)
	// GetMissionResult returns the current status/result of a mission.
	GetMissionResult(ctx context.Context, in *MissionResultRequest, opts ...grpc.CallOption) (*MissionResultResponse, error)
}

type orchestratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorServiceClient(cc grpc.ClientConnInterface) OrchestratorServiceClient {
	return &orchestratorServiceClient{cc}
}

func (c *orchestratorServiceClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) ReportHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_ReportHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) RequestSecret(ctx context.Context, in *RequestSecretRequest, opts ...grpc.CallOption) (*RequestSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestSecretResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_RequestSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) SubmitMission(ctx context.Context, in *SubmitMissionRequest, opts ...grpc.CallOption) (*SubmitMissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitMissionResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_SubmitMission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) GetSwarmStatus(ctx context.Context, in *SwarmStatusRequest, opts ...grpc.CallOption) (*SwarmStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwarmStatusResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_GetSwarmStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) GetMissionResult(ctx context.Context, in *MissionResultRequest, opts ...grpc.CallOption) (*MissionResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MissionResultResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_GetMissionResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorServiceServer is the server API for OrchestratorService service.
// All implementations must embed UnimplementedOrchestratorServiceServer
// for forward compatibility.
//
// OrchestratorService runs on the Global Orchestrator to receive node check-ins.
type OrchestratorServiceServer interface {
	// RegisterNode is called by a node when it joins the network.
	RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	// ReportHeartbeat is called periodically by nodes to report utilization.
	ReportHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// RequestSecret is called by nodes when they need sensitive data (e.g. login).
	// This triggers a user authorization flow on the Orchestrator host.
	RequestSecret(context.Context, *RequestSecretRequest) (*RequestSecretResponse, error)
	// SubmitMission is called by an Initiator (e.g. Mobile) to start a new mission.
	SubmitMission(context.Context, *SubmitMissionRequest) (*SubmitMissionResponse, error)
	// GetSwarmStatus returns the live state of all registered nodes.
	GetSwarmStatus(context.Context, *SwarmStatusRequest) (*SwarmStatusResponse, error)
	// GetMissionResult returns the current status/result of a mission.
	GetMissionResult(context.Context, *MissionResultRequest) (*MissionResultResponse, error)
	mustEmbedUnimplementedOrchestratorServiceServer()
}

// UnimplementedOrchestratorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestratorServiceServer struct{}

func (UnimplementedOrchestratorServiceServer) RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedOrchestratorServiceServer) ReportHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportHeartbeat not implemented")
}
func (UnimplementedOrchestratorServiceServer) RequestSecret(context.Context, *RequestSecretRequest) (*RequestSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestSecret not implemented")
}
func (UnimplementedOrchestratorServiceServer) SubmitMission(context.Context, *SubmitMissionRequest) (*SubmitMissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitMission not implemented")
}
func (UnimplementedOrchestratorServiceServer) GetSwarmStatus(context.Context, *SwarmStatusRequest) (*SwarmStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSwarmStatus not implemented")
}
func (UnimplementedOrchestratorServiceServer) GetMissionResult(context.Context, *MissionResultRequest) (*MissionResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMissionResult not implemented")
}
func (UnimplementedOrchestratorServiceServer) mustEmbedUnimplementedOrchestratorServiceServer() {}
func (UnimplementedOrchestratorServiceServer) testEmbeddedByValue()                             {}

// UnsafeOrchestratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorServiceServer will
// result in compilation errors.
type UnsafeOrchestratorServiceServer interface {
	mustEmbedUnimplementedOrchestratorServiceServer()
}

func RegisterOrchestratorServiceServer(s grpc.ServiceRegistrar, srv OrchestratorServiceServer) {
	// If the following call panics, it indicates UnimplementedOrchestratorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrchestratorService_ServiceDesc, srv)
}

func _OrchestratorService_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_ReportHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).ReportHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_ReportHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).ReportHeartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_RequestSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).RequestSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_RequestSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).RequestSecret(ctx, req.(*RequestSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_SubmitMission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitMissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).SubmitMission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_SubmitMission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).SubmitMission(ctx, req.(*SubmitMissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_GetSwarmStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwarmStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).GetSwarmStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_GetSwarmStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).GetSwarmStatus(ctx, req.(*SwarmStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_GetMissionResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MissionResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).GetMissionResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_GetMissionResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).GetMissionResult(ctx, req.(*MissionResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrchestratorService_ServiceDesc is the grpc.ServiceDesc for OrchestratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swarm.OrchestratorService",
	HandlerType: (*OrchestratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _OrchestratorService_RegisterNode_Handler,
		},
		{
			MethodName: "ReportHeartbeat",
			Handler:    _OrchestratorService_ReportHeartbeat_Handler,
		},
		{
			MethodName: "RequestSecret",
			Handler:    _OrchestratorService_RequestSecret_Handler,
		},
		{
			MethodName: "SubmitMission",
			Handler:    _OrchestratorService_SubmitMission_Handler,
		},
		{
			MethodName: "GetSwarmStatus",
			Handler:    _OrchestratorService_GetSwarmStatus_Handler,
		},
		{
			MethodName: "GetMissionResult",
			Handler:    _OrchestratorService_GetMissionResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/swarm/proto/swarm.proto",
}
