// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: pkg/swarm/proto/swarm.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitMissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Instruction   string                 `protobuf:"bytes,2,opt,name=instruction,proto3" json:"instruction,omitempty"`
	MissionId     string                 `protobuf:"bytes,3,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitMissionRequest) Reset() {
	*x = SubmitMissionRequest{}
	mi := &file_pkg_swarm_proto_swarm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitMissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitMissionRequest) ProtoMessage() {}

func (x *SubmitMissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_swarm_proto_swarm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitMissionRequest.ProtoReflect.Descriptor instead.
func (*SubmitMissionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_swarm_proto_swarm_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitMissionRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SubmitMissionRequest) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

func (x *SubmitMissionRequest) GetMissionId() string {
	if x != nil {
		return x.MissionId
	}
	return ""
}

type SubmitMissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitMissionResponse) Reset() {
	*x = SubmitMissionResponse{}
	mi := &file_pkg_swarm_proto_swarm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitMissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitMissionResponse) ProtoMessage() {}

func (x *SubmitMissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_swarm_proto_swarm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitMissionResponse.ProtoReflect.Descriptor instead.
func (*SubmitMissionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_swarm_proto_swarm_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitMissionResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SubmitMissionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RequestSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MissionId     string                 `protobuf:"bytes,1,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	Site          string                 `protobuf:"bytes,2,opt,name=site,proto3" json:"site,omitempty"`
	SecretKey     string                 `protobuf:"bytes,3,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"` // e.g. "password", "bank_account"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestSecretRequest) Reset() {
	*x = RequestSecretRequest{}
	mi := &file_pkg_swarm_proto_swarm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSecretRequest) ProtoMessage() {}

func (x *RequestSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_swarm_proto_swarm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSecretRequest.ProtoReflect.Descriptor instead.
func (*RequestSecretRequest) Descriptor() ([]byte, []int) {
	return file_pkg_swarm_proto_swarm_proto_rawDescGZIP(), []int{2}
}

func (x *RequestSecretRequest) GetMissionId() string {
	if x != nil {
		return x.MissionId
	}
	return ""
}

func (x *RequestSecretRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *RequestSecretRequest) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

type RequestSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authorized    bool                   `protobuf:"varint,1,opt,name=authorized,proto3" json:"authorized,omitempty"`
	SecretValue   string                 `protobuf:"bytes,2,opt,name=secret_value,json=secretValue,proto3" json:"secret_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestSecretResponse) Reset() {
	*x = RequestSecretResponse{}
	mi := &file_pkg_swarm_proto_swarm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSecretResponse) ProtoMessage() {}

func (x *RequestSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_swarm_proto_swarm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSecretResponse.ProtoReflect.Descriptor instead.
func (*RequestSecretResponse) Descriptor() ([]byte, []int) {
	return file_pkg_swarm_proto_swarm_proto_rawDescGZIP(), []int{3}
}

func (x *RequestSecretResponse) GetAuthorized() bool {
	if x != nil {
		return x.Authorized
	}
	return false
}

func (x *RequestSecretResponse) GetSecretValue() string {
	if x != nil {
		return x.SecretValue
	}
	return ""
}

type SpawnAgentRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Url               string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	SystemInstruction string                 `protobuf:"bytes,2,opt,name=system_instruction,json=systemInstruction,proto3" json:"system_instruction,omitempty"`
	MissionId         string                 `protobuf:"bytes,3,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	InstanceId        string                 `protobuf:"bytes,4,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SpawnAgentRequest) Reset() {
	*x = SpawnAgentRequest{}
	mi := &file_pkg_swarm_proto_swarm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnAgentRequest) ProtoMessage() {}

func (x *SpawnAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_swarm_proto_swarm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnAgentRequest.ProtoReflect.Descriptor instead.
func (*SpawnAgentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_swarm_proto_swarm_proto_rawDescGZIP(), []int{4}
}

func (x *SpawnAgentRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SpawnAgentRequest) GetSystemInstruction() string {
	if x != nil {
		return x.SystemInstruction
	}
	return ""
}

func (x *SpawnAgentRequest) GetMissionId() string {
	if x != nil {
		return x.MissionId
	}
	return ""
}

func (x *SpawnAgentRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type SpawnAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ResultJson    string                 `protobuf:"bytes,3,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	Screenshot    []byte                 `protobuf:"bytes,4,opt,name=screenshot,proto3" json:"screenshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnAgentResponse) Reset() {
	*x = SpawnAgentResponse{}
	mi := &file_pkg_swarm_proto_swarm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnAgentResponse) ProtoMessage() {}

func (x *SpawnAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_swarm_proto_swarm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnAgentResponse.ProtoReflect.Descriptor instead.
func (*SpawnAgentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_swarm_proto_swarm_proto_rawDescGZIP(), []int{5}
}

func (x *SpawnAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SpawnAgentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SpawnAgentResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *SpawnAgentResponse) GetScreenshot() []byte {
	if x != nil {
		return x.Screenshot
	}
	return nil
}

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Tier          string                 `protobuf:"bytes,2,opt,name=tier,proto3" json:"tier,omitempty"` // "Rack", "PC", "Laptop"
	MaxSimops     int32                  `protobuf:"varint,3,opt,name=max_simops,json=maxSimops,proto3" json:"max_simops,omitempty"`
	LoadedModels  []string               `protobuf:"bytes,4,rep,name=loaded_models,json=loadedModels,proto3" json:"loaded_models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_pkg_swarm_proto_swarm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_swarm_proto_swarm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_swarm_proto_swarm_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterNodeRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RegisterNodeRequest) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *RegisterNodeRequest) GetMaxSimops() int32 {
	if x != nil {
		return x.MaxSimops
	}
	return 0
}

func (x *RegisterNodeRequest) GetLoadedModels() []string {
	if x != nil {
		return x.LoadedModels
	}
	return nil
}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_pkg_swarm_proto_swarm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_swarm_proto_swarm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_swarm_proto_swarm_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Endpoint       string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	CurrentSimops  int32                  `protobuf:"varint,2,opt,name=current_simops,json=currentSimops,proto3" json:"current_simops,omitempty"`
	CpuUtilization float32                `protobuf:"fixed32,3,opt,name=cpu_utilization,json=cpuUtilization,proto3" json:"cpu_utilization,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_pkg_swarm_proto_swarm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_swarm_proto_swarm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_pkg_swarm_proto_swarm_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *HeartbeatRequest) GetCurrentSimops() int32 {
	if x != nil {
		return x.CurrentSimops
	}
	return 0
}

func (x *HeartbeatRequest) GetCpuUtilization() float32 {
	if x != nil {
		return x.CpuUtilization
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_pkg_swarm_proto_swarm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_swarm_proto_swarm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_swarm_proto_swarm_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SwarmStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwarmStatusRequest) Reset() {
	*x = SwarmStatusRequest{}
	mi := &file_pkg_swarm_proto_swarm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwarmStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwarmStatusRequest) ProtoMessage() {}

func (x *SwarmStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_swarm_proto_swarm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwarmStatusRequest.ProtoReflect.Descriptor instead.
func (*SwarmStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_swarm_proto_swarm_proto_rawDescGZIP(), []int{10}
}

type SwarmStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Nodes          []*NodeStatus          `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	ActiveMissions int32                  `protobuf:"varint,2,opt,name=active_missions,json=activeMissions,proto3" json:"active_missions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SwarmStatusResponse) Reset() {
	*x = SwarmStatusResponse{}
	mi := &file_pkg_swarm_proto_swarm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwarmStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwarmStatusResponse) ProtoMessage() {}

func (x *SwarmStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_swarm_proto_swarm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwarmStatusResponse.ProtoReflect.Descriptor instead.
func (*SwarmStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_swarm_proto_swarm_proto_rawDescGZIP(), []int{11}
}

func (x *SwarmStatusResponse) GetNodes() []*NodeStatus {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *SwarmStatusResponse) GetActiveMissions() int32 {
	if x != nil {
		return x.ActiveMissions
	}
	return 0
}

type NodeStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Endpoint       string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Tier           string                 `protobuf:"bytes,2,opt,name=tier,proto3" json:"tier,omitempty"`
	CpuUtilization float32                `protobuf:"fixed32,3,opt,name=cpu_utilization,json=cpuUtilization,proto3" json:"cpu_utilization,omitempty"`
	CurrentSimops  int32                  `protobuf:"varint,4,opt,name=current_simops,json=currentSimops,proto3" json:"current_simops,omitempty"`
	LastSeenMs     int64                  `protobuf:"varint,5,opt,name=last_seen_ms,json=lastSeenMs,proto3" json:"last_seen_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_pkg_swarm_proto_swarm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_swarm_proto_swarm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_pkg_swarm_proto_swarm_proto_rawDescGZIP(), []int{12}
}

func (x *NodeStatus) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *NodeStatus) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *NodeStatus) GetCpuUtilization() float32 {
	if x != nil {
		return x.CpuUtilization
	}
	return 0
}

func (x *NodeStatus) GetCurrentSimops() int32 {
	if x != nil {
		return x.CurrentSimops
	}
	return 0
}

func (x *NodeStatus) GetLastSeenMs() int64 {
	if x != nil {
		return x.LastSeenMs
	}
	return 0
}

type MissionResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MissionId     string                 `protobuf:"bytes,1,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissionResultRequest) Reset() {
	*x = MissionResultRequest{}
	mi := &file_pkg_swarm_proto_swarm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissionResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionResultRequest) ProtoMessage() {}

func (x *MissionResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_swarm_proto_swarm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionResultRequest.ProtoReflect.Descriptor instead.
func (*MissionResultRequest) Descriptor() ([]byte, []int) {
	return file_pkg_swarm_proto_swarm_proto_rawDescGZIP(), []int{13}
}

func (x *MissionResultRequest) GetMissionId() string {
	if x != nil {
		return x.MissionId
	}
	return ""
}

type MissionResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MissionId     string                 `protobuf:"bytes,1,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ResultJson    string                 `protobuf:"bytes,3,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	DispatchedTo  string                 `protobuf:"bytes,4,opt,name=dispatched_to,json=dispatchedTo,proto3" json:"dispatched_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissionResultResponse) Reset() {
	*x = MissionResultResponse{}
	mi := &file_pkg_swarm_proto_swarm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissionResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionResultResponse) ProtoMessage() {}

func (x *MissionResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_swarm_proto_swarm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionResultResponse.ProtoReflect.Descriptor instead.
func (*MissionResultResponse) Descriptor() ([]byte, []int) {
	return file_pkg_swarm_proto_swarm_proto_rawDescGZIP(), []int{14}
}

func (x *MissionResultResponse) GetMissionId() string {
	if x != nil {
		return x.MissionId
	}
	return ""
}

func (x *MissionResultResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MissionResultResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *MissionResultResponse) GetDispatchedTo() string {
	if x != nil {
		return x.DispatchedTo
	}
	return ""
}

var File_pkg_swarm_proto_swarm_proto protoreflect.FileDescriptor

const file_pkg_swarm_proto_swarm_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/swarm/proto/swarm.proto\x12\x05swarm\"i\n" +
	"\x14SubmitMissionRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12 \n" +
	"\vinstruction\x18\x02 \x01(\tR\vinstruction\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x03 \x01(\tR\tmissionId\"M\n" +
	"\x15SubmitMissionResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"h\n" +
	"\x14RequestSecretRequest\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x01 \x01(\tR\tmissionId\x12\x12\n" +
	"\x04site\x18\x02 \x01(\tR\x04site\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x03 \x01(\tR\tsecretKey\"Z\n" +
	"\x15RequestSecretResponse\x12\x1e\n" +
	"\n" +
	"authorized\x18\x01 \x01(\bR\n" +
	"authorized\x12!\n" +
	"\fsecret_value\x18\x02 \x01(\tR\vsecretValue\"\x94\x01\n" +
	"\x11SpawnAgentRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12-\n" +
	"\x12system_instruction\x18\x02 \x01(\tR\x11systemInstruction\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x03 \x01(\tR\tmissionId\x12\x1f\n" +
	"\vinstance_id\x18\x04 \x01(\tR\n" +
	"instanceId\"\x89\x01\n" +
	"\x12SpawnAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vresult_json\x18\x03 \x01(\tR\n" +
	"resultJson\x12\x1e\n" +
	"\n" +
	"screenshot\x18\x04 \x01(\fR\n" +
	"screenshot\"\x89\x01\n" +
	"\x13RegisterNodeRequest\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x12\n" +
	"\x04tier\x18\x02 \x01(\tR\x04tier\x12\x1d\n" +
	"\n" +
	"max_simops\x18\x03 \x01(\x05R\tmaxSimops\x12#\n" +
	"\rloaded_models\x18\x04 \x03(\tR\floadedModels\"J\n" +
	"\x14RegisterNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"~\n" +
	"\x10HeartbeatRequest\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12%\n" +
	"\x0ecurrent_simops\x18\x02 \x01(\x05R\rcurrentSimops\x12'\n" +
	"\x0fcpu_utilization\x18\x03 \x01(\x02R\x0ecpuUtilization\"-\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x14\n" +
	"\x12SwarmStatusRequest\"g\n" +
	"\x13SwarmStatusResponse\x12'\n" +
	"\x05nodes\x18\x01 \x03(\v2\x11.swarm.NodeStatusR\x05nodes\x12'\n" +
	"\x0factive_missions\x18\x02 \x01(\x05R\x0eactiveMissions\"\xae\x01\n" +
	"\n" +
	"NodeStatus\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x12\n" +
	"\x04tier\x18\x02 \x01(\tR\x04tier\x12'\n" +
	"\x0fcpu_utilization\x18\x03 \x01(\x02R\x0ecpuUtilization\x12%\n" +
	"\x0ecurrent_simops\x18\x04 \x01(\x05R\rcurrentSimops\x12 \n" +
	"\flast_seen_ms\x18\x05 \x01(\x03R\n" +
	"lastSeenMs\"5\n" +
	"\x14MissionResultRequest\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x01 \x01(\tR\tmissionId\"\x94\x01\n" +
	"\x15MissionResultResponse\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x01 \x01(\tR\tmissionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vresult_json\x18\x03 \x01(\tR\n" +
	"resultJson\x12#\n" +
	"\rdispatched_to\x18\x04 \x01(\tR\fdispatchedTo2Q\n" +
	"\fSwarmService\x12A\n" +
	"\n" +
	"SpawnAgent\x12\x18.swarm.SpawnAgentRequest\x1a\x19.swarm.SpawnAgentResponse2\xd4\x03\n" +
	"\x13OrchestratorService\x12G\n" +
	"\fRegisterNode\x12\x1a.swarm.RegisterNodeRequest\x1a\x1b.swarm.RegisterNodeResponse\x12D\n" +
	"\x0fReportHeartbeat\x12\x17.swarm.HeartbeatRequest\x1a\x18.swarm.HeartbeatResponse\x12J\n" +
	"\rRequestSecret\x12\x1b.swarm.RequestSecretRequest\x1a\x1c.swarm.RequestSecretResponse\x12J\n" +
	"\rSubmitMission\x12\x1b.swarm.SubmitMissionRequest\x1a\x1c.swarm.SubmitMissionResponse\x12G\n" +
	"\x0eGetSwarmStatus\x12\x19.swarm.SwarmStatusRequest\x1a\x1a.swarm.SwarmStatusResponse\x12M\n" +
	"\x10GetMissionResult\x12\x1b.swarm.MissionResultRequest\x1a\x1c.swarm.MissionResultResponseBAZ?github.com/reclamation-admin/agentic-browser-go/pkg/swarm/protob\x06proto3"

var (
	file_pkg_swarm_proto_swarm_proto_rawDescOnce sync.Once
	file_pkg_swarm_proto_swarm_proto_rawDescData []byte
)

func file_pkg_swarm_proto_swarm_proto_rawDescGZIP() []byte {
	file_pkg_swarm_proto_swarm_proto_rawDescOnce.Do(func() {
		file_pkg_swarm_proto_swarm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_swarm_proto_swarm_proto_rawDesc), len(file_pkg_swarm_proto_swarm_proto_rawDesc)))
	})
	return file_pkg_swarm_proto_swarm_proto_rawDescData
}

var file_pkg_swarm_proto_swarm_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_pkg_swarm_proto_swarm_proto_goTypes = []any{
	(*SubmitMissionRequest)(nil),  // 0: swarm.SubmitMissionRequest
	(*SubmitMissionResponse)(nil), // 1: swarm.SubmitMissionResponse
	(*RequestSecretRequest)(nil),  // 2: swarm.RequestSecretRequest
	(*RequestSecretResponse)(nil), // 3: swarm.RequestSecretResponse
	(*SpawnAgentRequest)(nil),     // 4: swarm.SpawnAgentRequest
	(*SpawnAgentResponse)(nil),    // 5: swarm.SpawnAgentResponse
	(*RegisterNodeRequest)(nil),   // 6: swarm.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),  // 7: swarm.RegisterNodeResponse
	(*HeartbeatRequest)(nil),      // 8: swarm.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 9: swarm.HeartbeatResponse
	(*SwarmStatusRequest)(nil),    // 10: swarm.SwarmStatusRequest
	(*SwarmStatusResponse)(nil),   // 11: swarm.SwarmStatusResponse
	(*NodeStatus)(nil),            // 12: swarm.NodeStatus
	(*MissionResultRequest)(nil),  // 13: swarm.MissionResultRequest
	(*MissionResultResponse)(nil), // 14: swarm.MissionResultResponse
}
var file_pkg_swarm_proto_swarm_proto_depIdxs = []int32{
	12, // 0: swarm.SwarmStatusResponse.nodes:type_name -> swarm.NodeStatus
	4,  // 1: swarm.SwarmService.SpawnAgent:input_type -> swarm.SpawnAgentRequest
	6,  // 2: swarm.OrchestratorService.RegisterNode:input_type -> swarm.RegisterNodeRequest
	8,  // 3: swarm.OrchestratorService.ReportHeartbeat:input_type -> swarm.HeartbeatRequest
	2,  // 4: swarm.OrchestratorService.RequestSecret:input_type -> swarm.RequestSecretRequest
	0,  // 5: swarm.OrchestratorService.SubmitMission:input_type -> swarm.SubmitMissionRequest
	10, // 6: swarm.OrchestratorService.GetSwarmStatus:input_type -> swarm.SwarmStatusRequest
	13, // 7: swarm.OrchestratorService.GetMissionResult:input_type -> swarm.MissionResultRequest
	5,  // 8: swarm.SwarmService.SpawnAgent:output_type -> swarm.SpawnAgentResponse
	7,  // 9: swarm.OrchestratorService.RegisterNode:output_type -> swarm.RegisterNodeResponse
	9,  // 10: swarm.OrchestratorService.ReportHeartbeat:output_type -> swarm.HeartbeatResponse
	3,  // 11: swarm.OrchestratorService.RequestSecret:output_type -> swarm.RequestSecretResponse
	1,  // 12: swarm.OrchestratorService.SubmitMission:output_type -> swarm.SubmitMissionResponse
	11, // 13: swarm.OrchestratorService.GetSwarmStatus:output_type -> swarm.SwarmStatusResponse
	14, // 14: swarm.OrchestratorService.GetMissionResult:output_type -> swarm.MissionResultResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_swarm_proto_swarm_proto_init() }
func file_pkg_swarm_proto_swarm_proto_init() {
	if File_pkg_swarm_proto_swarm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_swarm_proto_swarm_proto_rawDesc), len(file_pkg_swarm_proto_swarm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_swarm_proto_swarm_proto_goTypes,
		DependencyIndexes: file_pkg_swarm_proto_swarm_proto_depIdxs,
		MessageInfos:      file_pkg_swarm_proto_swarm_proto_msgTypes,
	}.Build()
	File_pkg_swarm_proto_swarm_proto = out.File
	file_pkg_swarm_proto_swarm_proto_goTypes = nil
	file_pkg_swarm_proto_swarm_proto_depIdxs = nil
}
