use std::collections::HashMap;

#[derive(Debug, Clone, PartialEq)]
pub enum ServiceWorkerState {
    Parsing,
    Installing,
    Installed,
    Activating,
    Activated,
    Redundant,
}

#[derive(Debug, Clone)]
pub struct CachedResponse {
    pub url: String,
    pub status: u16,
    pub headers: Vec<(String, String)>,
    pub body: String,
    pub cached_at_ms: u64,
}

/// Fetch event interception result.
#[derive(Debug, Clone)]
pub enum FetchInterceptResult {
    /// Respond from cache.
    CachedResponse(CachedResponse),
    /// Pass through to network (no cache match).
    NetworkPassthrough,
    /// Custom response generated by the service worker.
    CustomResponse { status: u16, body: String },
}

/// Background sync registration.
#[derive(Debug, Clone)]
pub struct BackgroundSyncRegistration {
    pub tag: String,
    pub min_interval_ms: u64,
    pub pending: bool,
}

/// Push message dispatched to the service worker.
#[derive(Debug, Clone)]
pub struct PushMessage {
    pub title: String,
    pub body: String,
    pub data: String,
    pub icon_url: Option<String>,
}

pub struct CacheStorageEngine {
    pub caches: HashMap<String, HashMap<String, CachedResponse>>,
}

impl Default for CacheStorageEngine {
    fn default() -> Self {
        Self::new()
    }
}

impl CacheStorageEngine {
    pub fn new() -> Self {
        Self { caches: HashMap::new() }
    }

    pub fn put(&mut self, cache_name: &str, url: &str, status: u16, body: &str) {
        let cache = self.caches.entry(cache_name.to_string()).or_default();
        cache.insert(url.to_string(), CachedResponse {
            url: url.to_string(),
            status,
            headers: Vec::new(),
            body: body.to_string(),
            cached_at_ms: std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_millis() as u64)
                .unwrap_or(0),
        });
    }

    pub fn put_with_headers(&mut self, cache_name: &str, url: &str, status: u16, headers: Vec<(String, String)>, body: &str) {
        let cache = self.caches.entry(cache_name.to_string()).or_default();
        cache.insert(url.to_string(), CachedResponse {
            url: url.to_string(),
            status,
            headers,
            body: body.to_string(),
            cached_at_ms: std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_millis() as u64)
                .unwrap_or(0),
        });
    }

    pub fn match_url(&self, cache_name: &str, url: &str) -> Option<&CachedResponse> {
        self.caches.get(cache_name).and_then(|c| c.get(url))
    }

    /// Match across all caches (caches.match with no cache name).
    pub fn match_any(&self, url: &str) -> Option<&CachedResponse> {
        for cache in self.caches.values() {
            if let Some(resp) = cache.get(url) {
                return Some(resp);
            }
        }
        None
    }

    /// Delete a cached entry.
    pub fn delete(&mut self, cache_name: &str, url: &str) -> bool {
        if let Some(cache) = self.caches.get_mut(cache_name) {
            cache.remove(url).is_some()
        } else {
            false
        }
    }

    /// List all cached URLs in a cache.
    pub fn keys(&self, cache_name: &str) -> Vec<String> {
        self.caches.get(cache_name)
            .map(|c| c.keys().cloned().collect())
            .unwrap_or_default()
    }

    /// Delete an entire cache.
    pub fn delete_cache(&mut self, cache_name: &str) -> bool {
        self.caches.remove(cache_name).is_some()
    }
}

pub struct ServiceWorkerManager {
    pub script_url: String,
    pub scope: String,
    pub state: ServiceWorkerState,
    pub cache_storage: CacheStorageEngine,
    pub fetch_intercept_rules: Vec<FetchInterceptRule>,
    pub sync_registrations: Vec<BackgroundSyncRegistration>,
    pub push_queue: Vec<PushMessage>,
    pub install_time_ms: u64,
}

/// Rule for intercepting fetch events.
#[derive(Debug, Clone)]
pub struct FetchInterceptRule {
    pub url_pattern: String,
    pub cache_name: String,
    pub strategy: CacheStrategy,
}

#[derive(Debug, Clone, PartialEq)]
pub enum CacheStrategy {
    /// Cache first, fall back to network.
    CacheFirst,
    /// Network first, fall back to cache.
    NetworkFirst,
    /// Cache only — never hit network.
    CacheOnly,
    /// Network only — never use cache.
    NetworkOnly,
    /// Stale-while-revalidate: return cache immediately, update in background.
    StaleWhileRevalidate,
}

impl ServiceWorkerManager {
    pub fn register(script_url: &str) -> Self {
        Self {
            script_url: script_url.to_string(),
            scope: "/".to_string(),
            state: ServiceWorkerState::Installing,
            cache_storage: CacheStorageEngine::new(),
            fetch_intercept_rules: Vec::new(),
            sync_registrations: Vec::new(),
            push_queue: Vec::new(),
            install_time_ms: std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_millis() as u64)
                .unwrap_or(0),
        }
    }

    /// Transition through the service worker lifecycle.
    pub fn advance_lifecycle(&mut self) {
        self.state = match &self.state {
            ServiceWorkerState::Parsing | ServiceWorkerState::Installing => ServiceWorkerState::Installed,
            ServiceWorkerState::Installed => ServiceWorkerState::Activating,
            ServiceWorkerState::Activating => ServiceWorkerState::Activated,
            other => other.clone(),
        };
    }

    /// Force to redundant (e.g., replaced by a newer worker).
    pub fn mark_redundant(&mut self) {
        self.state = ServiceWorkerState::Redundant;
    }

    /// Set the scope for this service worker.
    pub fn set_scope(&mut self, scope: &str) {
        self.scope = scope.to_string();
    }

    /// Register a fetch interception rule.
    pub fn add_fetch_rule(&mut self, url_pattern: &str, cache_name: &str, strategy: CacheStrategy) {
        self.fetch_intercept_rules.push(FetchInterceptRule {
            url_pattern: url_pattern.to_string(),
            cache_name: cache_name.to_string(),
            strategy,
        });
    }

    /// Intercept a fetch request based on registered rules.
    pub fn intercept_fetch(&self, url: &str) -> FetchInterceptResult {
        for rule in &self.fetch_intercept_rules {
            if url.contains(&rule.url_pattern) {
                return match rule.strategy {
                    CacheStrategy::CacheFirst | CacheStrategy::CacheOnly | CacheStrategy::StaleWhileRevalidate => {
                        if let Some(resp) = self.cache_storage.match_url(&rule.cache_name, url) {
                            FetchInterceptResult::CachedResponse(resp.clone())
                        } else if rule.strategy == CacheStrategy::CacheOnly {
                            FetchInterceptResult::CustomResponse { status: 504, body: "Gateway Timeout: not in cache".to_string() }
                        } else {
                            FetchInterceptResult::NetworkPassthrough
                        }
                    }
                    CacheStrategy::NetworkFirst | CacheStrategy::NetworkOnly => {
                        FetchInterceptResult::NetworkPassthrough
                    }
                };
            }
        }
        FetchInterceptResult::NetworkPassthrough
    }

    /// Register a background sync task.
    pub fn register_sync(&mut self, tag: &str, min_interval_ms: u64) {
        if !self.sync_registrations.iter().any(|r| r.tag == tag) {
            self.sync_registrations.push(BackgroundSyncRegistration {
                tag: tag.to_string(),
                min_interval_ms,
                pending: true,
            });
        }
    }

    /// Get pending sync tasks.
    pub fn pending_sync_tags(&self) -> Vec<String> {
        self.sync_registrations.iter().filter(|r| r.pending).map(|r| r.tag.clone()).collect()
    }

    /// Mark a sync task as completed.
    pub fn complete_sync(&mut self, tag: &str) {
        if let Some(reg) = self.sync_registrations.iter_mut().find(|r| r.tag == tag) {
            reg.pending = false;
        }
    }

    /// Dispatch a push message to the service worker.
    pub fn dispatch_push(&mut self, title: &str, body: &str, data: &str, icon: Option<&str>) {
        self.push_queue.push(PushMessage {
            title: title.to_string(),
            body: body.to_string(),
            data: data.to_string(),
            icon_url: icon.map(|s| s.to_string()),
        });
    }

    /// Drain the push queue.
    pub fn drain_push_queue(&mut self) -> Vec<PushMessage> {
        std::mem::take(&mut self.push_queue)
    }

    /// Unregister the service worker.
    pub fn unregister(&mut self) {
        self.state = ServiceWorkerState::Redundant;
        self.fetch_intercept_rules.clear();
        self.sync_registrations.clear();
    }
}
