use std::collections::HashMap;

#[derive(Debug, Clone, PartialEq)]
pub enum ServiceWorkerState {
    Parsing,
    Installing,
    Installed,
    Activating,
    Activated,
    Redundant,
}

#[derive(Debug, Clone)]
pub struct CachedResponse {
    pub url: String,
    pub status: u16,
    pub headers: Vec<(String, String)>,
    pub body: String,
    pub cached_at_ms: u64,
}

/// Fetch event interception result.
#[derive(Debug, Clone)]
pub enum FetchInterceptResult {
    /// Respond from cache.
    CachedResponse(CachedResponse),
    /// Pass through to network (no cache match).
    NetworkPassthrough,
    /// Custom response generated by the service worker.
    CustomResponse { status: u16, body: String },
}

/// Background sync registration.
#[derive(Debug, Clone)]
pub struct BackgroundSyncRegistration {
    pub tag: String,
    pub min_interval_ms: u64,
    pub pending: bool,
}

/// Push message dispatched to the service worker.
#[derive(Debug, Clone)]
pub struct PushMessage {
    pub title: String,
    pub body: String,
    pub data: String,
    pub icon_url: Option<String>,
}

pub struct CacheStorageEngine {
    pub caches: HashMap<String, HashMap<String, CachedResponse>>,
}

impl Default for CacheStorageEngine {
    fn default() -> Self {
        Self::new()
    }
}

impl CacheStorageEngine {
    pub fn new() -> Self {
        Self { caches: HashMap::new() }
    }

    pub fn put(&mut self, cache_name: &str, url: &str, status: u16, body: &str) {
        let cache = self.caches.entry(cache_name.to_string()).or_default();
        cache.insert(url.to_string(), CachedResponse {
            url: url.to_string(),
            status,
            headers: Vec::new(),
            body: body.to_string(),
            cached_at_ms: std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_millis() as u64)
                .unwrap_or(0),
        });
    }

    pub fn put_with_headers(&mut self, cache_name: &str, url: &str, status: u16, headers: Vec<(String, String)>, body: &str) {
        let cache = self.caches.entry(cache_name.to_string()).or_default();
        cache.insert(url.to_string(), CachedResponse {
            url: url.to_string(),
            status,
            headers,
            body: body.to_string(),
            cached_at_ms: std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_millis() as u64)
                .unwrap_or(0),
        });
    }

    pub fn match_url(&self, cache_name: &str, url: &str) -> Option<&CachedResponse> {
        self.caches.get(cache_name).and_then(|c| c.get(url))
    }

    /// Match across all caches (caches.match with no cache name).
    pub fn match_any(&self, url: &str) -> Option<&CachedResponse> {
        for cache in self.caches.values() {
            if let Some(resp) = cache.get(url) {
                return Some(resp);
            }
        }
        None
    }

    /// Delete a cached entry.
    pub fn delete(&mut self, cache_name: &str, url: &str) -> bool {
        if let Some(cache) = self.caches.get_mut(cache_name) {
            cache.remove(url).is_some()
        } else {
            false
        }
    }

    /// List all cached URLs in a cache.
    pub fn keys(&self, cache_name: &str) -> Vec<String> {
        self.caches.get(cache_name)
            .map(|c| c.keys().cloned().collect())
            .unwrap_or_default()
    }

    /// Delete an entire cache.
    pub fn delete_cache(&mut self, cache_name: &str) -> bool {
        self.caches.remove(cache_name).is_some()
    }
}

pub struct ServiceWorkerManager {
    pub script_url: String,
    pub scope: String,
    pub state: ServiceWorkerState,
    pub cache_storage: CacheStorageEngine,
    pub fetch_intercept_rules: Vec<FetchInterceptRule>,
    pub sync_registrations: Vec<BackgroundSyncRegistration>,
    pub push_queue: Vec<PushMessage>,
    pub install_time_ms: u64,
}

/// Rule for intercepting fetch events.
#[derive(Debug, Clone)]
pub struct FetchInterceptRule {
    pub url_pattern: String,
    pub cache_name: String,
    pub strategy: CacheStrategy,
}

#[derive(Debug, Clone, PartialEq)]
pub enum CacheStrategy {
    /// Cache first, fall back to network.
    CacheFirst,
    /// Network first, fall back to cache.
    NetworkFirst,
    /// Cache only — never hit network.
    CacheOnly,
    /// Network only — never use cache.
    NetworkOnly,
    /// Stale-while-revalidate: return cache immediately, update in background.
    StaleWhileRevalidate,
}

impl ServiceWorkerManager {
    pub fn register(script_url: &str) -> Self {
        Self {
            script_url: script_url.to_string(),
            scope: "/".to_string(),
            state: ServiceWorkerState::Installing,
            cache_storage: CacheStorageEngine::new(),
            fetch_intercept_rules: Vec::new(),
            sync_registrations: Vec::new(),
            push_queue: Vec::new(),
            install_time_ms: std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_millis() as u64)
                .unwrap_or(0),
        }
    }

    /// Transition through the service worker lifecycle.
    pub fn advance_lifecycle(&mut self) {
        self.state = match &self.state {
            ServiceWorkerState::Parsing | ServiceWorkerState::Installing => ServiceWorkerState::Installed,
            ServiceWorkerState::Installed => ServiceWorkerState::Activating,
            ServiceWorkerState::Activating => ServiceWorkerState::Activated,
            other => other.clone(),
        };
    }

    /// Force to redundant (e.g., replaced by a newer worker).
    pub fn mark_redundant(&mut self) {
        self.state = ServiceWorkerState::Redundant;
    }

    /// Set the scope for this service worker.
    pub fn set_scope(&mut self, scope: &str) {
        self.scope = scope.to_string();
    }

    /// Register a fetch interception rule.
    pub fn add_fetch_rule(&mut self, url_pattern: &str, cache_name: &str, strategy: CacheStrategy) {
        self.fetch_intercept_rules.push(FetchInterceptRule {
            url_pattern: url_pattern.to_string(),
            cache_name: cache_name.to_string(),
            strategy,
        });
    }

    /// Intercept a fetch request based on registered rules.
    pub fn intercept_fetch(&self, url: &str) -> FetchInterceptResult {
        for rule in &self.fetch_intercept_rules {
            if url.contains(&rule.url_pattern) {
                return match rule.strategy {
                    CacheStrategy::CacheFirst | CacheStrategy::CacheOnly | CacheStrategy::StaleWhileRevalidate => {
                        if let Some(resp) = self.cache_storage.match_url(&rule.cache_name, url) {
                            FetchInterceptResult::CachedResponse(resp.clone())
                        } else if rule.strategy == CacheStrategy::CacheOnly {
                            FetchInterceptResult::CustomResponse { status: 504, body: "Gateway Timeout: not in cache".to_string() }
                        } else {
                            FetchInterceptResult::NetworkPassthrough
                        }
                    }
                    CacheStrategy::NetworkFirst | CacheStrategy::NetworkOnly => {
                        FetchInterceptResult::NetworkPassthrough
                    }
                };
            }
        }
        FetchInterceptResult::NetworkPassthrough
    }

    /// Register a background sync task.
    pub fn register_sync(&mut self, tag: &str, min_interval_ms: u64) {
        if !self.sync_registrations.iter().any(|r| r.tag == tag) {
            self.sync_registrations.push(BackgroundSyncRegistration {
                tag: tag.to_string(),
                min_interval_ms,
                pending: true,
            });
        }
    }

    /// Get pending sync tasks.
    pub fn pending_sync_tags(&self) -> Vec<String> {
        self.sync_registrations.iter().filter(|r| r.pending).map(|r| r.tag.clone()).collect()
    }

    /// Mark a sync task as completed.
    pub fn complete_sync(&mut self, tag: &str) {
        if let Some(reg) = self.sync_registrations.iter_mut().find(|r| r.tag == tag) {
            reg.pending = false;
        }
    }

    /// Dispatch a push message to the service worker.
    pub fn dispatch_push(&mut self, title: &str, body: &str, data: &str, icon: Option<&str>) {
        self.push_queue.push(PushMessage {
            title: title.to_string(),
            body: body.to_string(),
            data: data.to_string(),
            icon_url: icon.map(|s| s.to_string()),
        });
    }

    /// Drain the push queue.
    pub fn drain_push_queue(&mut self) -> Vec<PushMessage> {
        std::mem::take(&mut self.push_queue)
    }

    /// Unregister the service worker.
    pub fn unregister(&mut self) {
        self.state = ServiceWorkerState::Redundant;
        self.fetch_intercept_rules.clear();
        self.sync_registrations.clear();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_cache_put_and_match() {
        let mut cache = CacheStorageEngine::new();
        cache.put("v1", "/index.html", 200, "<html>Hello</html>");
        let resp = cache.match_url("v1", "/index.html").unwrap();
        assert_eq!(resp.status, 200);
        assert_eq!(resp.body, "<html>Hello</html>");
    }

    #[test]
    fn test_cache_match_any() {
        let mut cache = CacheStorageEngine::new();
        cache.put("v1", "/a.html", 200, "a");
        cache.put("v2", "/b.html", 200, "b");
        assert!(cache.match_any("/b.html").is_some());
        assert!(cache.match_any("/c.html").is_none());
    }

    #[test]
    fn test_cache_delete() {
        let mut cache = CacheStorageEngine::new();
        cache.put("v1", "/x.html", 200, "x");
        assert!(cache.delete("v1", "/x.html"));
        assert!(cache.match_url("v1", "/x.html").is_none());
    }

    #[test]
    fn test_lifecycle_transitions() {
        let mut sw = ServiceWorkerManager::register("/sw.js");
        assert_eq!(sw.state, ServiceWorkerState::Installing);
        sw.advance_lifecycle(); // Installing -> Installed
        assert_eq!(sw.state, ServiceWorkerState::Installed);
        sw.advance_lifecycle(); // Installed -> Activating
        assert_eq!(sw.state, ServiceWorkerState::Activating);
        sw.advance_lifecycle(); // Activating -> Activated
        assert_eq!(sw.state, ServiceWorkerState::Activated);
    }

    #[test]
    fn test_fetch_intercept_cache_first() {
        let mut sw = ServiceWorkerManager::register("/sw.js");
        sw.cache_storage.put("assets", "/logo.png", 200, "PNG_DATA");
        sw.add_fetch_rule("/logo.png", "assets", CacheStrategy::CacheFirst);
        match sw.intercept_fetch("/logo.png") {
            FetchInterceptResult::CachedResponse(r) => assert_eq!(r.status, 200),
            _ => panic!("Expected cached response"),
        }
    }

    #[test]
    fn test_fetch_intercept_cache_only_miss() {
        let mut sw = ServiceWorkerManager::register("/sw.js");
        sw.add_fetch_rule("/missing", "assets", CacheStrategy::CacheOnly);
        match sw.intercept_fetch("/missing") {
            FetchInterceptResult::CustomResponse { status, .. } => assert_eq!(status, 504),
            _ => panic!("Expected 504 for cache-only miss"),
        }
    }

    #[test]
    fn test_background_sync() {
        let mut sw = ServiceWorkerManager::register("/sw.js");
        sw.register_sync("sync-messages", 5000);
        sw.register_sync("send-email", 10000);
        assert_eq!(sw.pending_sync_tags(), vec!["sync-messages", "send-email"]);
        sw.complete_sync("sync-messages");
        assert_eq!(sw.pending_sync_tags(), vec!["send-email"]);
    }

    #[test]
    fn test_push_dispatch_and_drain() {
        let mut sw = ServiceWorkerManager::register("/sw.js");
        sw.dispatch_push("New message", "Hello!", "{}", None);
        assert_eq!(sw.push_queue.len(), 1);
        let drained = sw.drain_push_queue();
        assert_eq!(drained.len(), 1);
        assert_eq!(drained[0].title, "New message");
        assert!(sw.push_queue.is_empty());
    }

    #[test]
    fn cache_put_with_headers() {
        let mut cache = CacheStorageEngine::new();
        cache.put_with_headers("v1", "/api", 200, vec![("Content-Type".into(), "application/json".into())], "{\"ok\":true}");
        let resp = cache.match_url("v1", "/api").unwrap();
        assert_eq!(resp.status, 200);
        assert_eq!(resp.headers[0].0, "Content-Type");
    }

    #[test]
    fn cache_keys_lists_urls() {
        let mut cache = CacheStorageEngine::new();
        cache.put("v1", "/a", 200, "a");
        cache.put("v1", "/b", 200, "b");
        let keys = cache.keys("v1");
        assert_eq!(keys.len(), 2);
        assert!(keys.contains(&"/a".to_string()));
    }

    #[test]
    fn cache_keys_nonexistent_returns_empty() {
        let cache = CacheStorageEngine::new();
        assert!(cache.keys("nope").is_empty());
    }

    #[test]
    fn delete_cache_removes_entire_cache() {
        let mut cache = CacheStorageEngine::new();
        cache.put("v1", "/a", 200, "a");
        cache.put("v1", "/b", 200, "b");
        assert!(cache.delete_cache("v1"));
        assert!(cache.keys("v1").is_empty());
        assert!(!cache.delete_cache("v1")); // already gone
    }

    #[test]
    fn delete_nonexistent_entry_returns_false() {
        let mut cache = CacheStorageEngine::new();
        cache.put("v1", "/a", 200, "a");
        assert!(!cache.delete("v1", "/nonexistent"));
        assert!(!cache.delete("nonexistent", "/a"));
    }

    #[test]
    fn lifecycle_parsing_to_installed() {
        let mut sw = ServiceWorkerManager::register("/sw.js");
        sw.state = ServiceWorkerState::Parsing;
        sw.advance_lifecycle();
        assert_eq!(sw.state, ServiceWorkerState::Installed);
    }

    #[test]
    fn mark_redundant_from_any_state() {
        let mut sw = ServiceWorkerManager::register("/sw.js");
        sw.mark_redundant();
        assert_eq!(sw.state, ServiceWorkerState::Redundant);
    }

    #[test]
    fn unregister_clears_rules_and_sync() {
        let mut sw = ServiceWorkerManager::register("/sw.js");
        sw.add_fetch_rule("/api", "cache", CacheStrategy::CacheFirst);
        sw.register_sync("tag1", 1000);
        sw.unregister();
        assert_eq!(sw.state, ServiceWorkerState::Redundant);
        assert!(sw.fetch_intercept_rules.is_empty());
        assert!(sw.sync_registrations.is_empty());
    }

    #[test]
    fn register_sync_deduplicates_tags() {
        let mut sw = ServiceWorkerManager::register("/sw.js");
        sw.register_sync("sync-messages", 5000);
        sw.register_sync("sync-messages", 10000); // duplicate
        assert_eq!(sw.sync_registrations.len(), 1);
    }

    #[test]
    fn intercept_fetch_network_first_always_passes_through() {
        let mut sw = ServiceWorkerManager::register("/sw.js");
        sw.cache_storage.put("assets", "/data.json", 200, "{\"cached\":true}");
        sw.add_fetch_rule("/data.json", "assets", CacheStrategy::NetworkFirst);
        match sw.intercept_fetch("/data.json") {
            FetchInterceptResult::NetworkPassthrough => {}
            _ => panic!("Expected NetworkPassthrough for NetworkFirst"),
        }
    }

    #[test]
    fn intercept_fetch_no_matching_rule_returns_passthrough() {
        let sw = ServiceWorkerManager::register("/sw.js");
        match sw.intercept_fetch("/anything") {
            FetchInterceptResult::NetworkPassthrough => {}
            _ => panic!("Expected NetworkPassthrough with no rules"),
        }
    }
}
