//! Velocity Router HTTP client.
//!
//! Provides a typed interface to the Velocity Model Router API for usage
//! tracking, assignment submission, cost monitoring, transparency data,
//! timeseries analytics, audit logs, and API key management.

use std::collections::HashMap;
use std::time::Duration;

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

/// Configuration for connecting to the Velocity Router.
#[derive(Debug, Clone)]
pub struct VelocityConfig {
    pub base_url: String,
    pub api_key: String,
}

impl VelocityConfig {
    /// Load from environment variables or config file.
    /// Checks VELOCITY_BASE_URL and VELOCITY_API_KEY env vars first,
    /// then falls back to ~/.velocity/config.toml.
    pub fn load() -> Result<Self> {
        // Try environment variables first.
        if let (Ok(url), Ok(key)) = (
            std::env::var("VELOCITY_BASE_URL"),
            std::env::var("VELOCITY_API_KEY"),
        ) {
            return Ok(Self {
                base_url: url,
                api_key: key,
            });
        }

        // Try ~/.velocity/config.toml with proper TOML parsing.
        if let Some(home) = dirs_next() {
            let config_path = home.join(".velocity").join("config.toml");
            if config_path.exists() {
                let content = std::fs::read_to_string(&config_path)
                    .context("failed to read ~/.velocity/config.toml")?;
                let parsed = parse_toml_simple(&content);
                if let (Some(url), Some(key)) = (
                    parsed.get("base_url").cloned(),
                    parsed.get("api_key").cloned(),
                ) {
                    return Ok(Self {
                        base_url: url,
                        api_key: key,
                    });
                }
            }
        }

        anyhow::bail!(
            "Velocity Router not configured.\n\
             Set VELOCITY_BASE_URL and VELOCITY_API_KEY environment variables,\n\
             or create ~/.velocity/config.toml with:\n\
             \n\
             base_url = \"http://localhost:8787\"\n\
             api_key = \"vr_standard_your_key_here\""
        )
    }

    /// Save configuration to ~/.velocity/config.toml.
    pub fn save(&self) -> Result<()> {
        if let Some(home) = dirs_next() {
            let config_dir = home.join(".velocity");
            std::fs::create_dir_all(&config_dir)
                .context("failed to create ~/.velocity directory")?;
            let config_path = config_dir.join("config.toml");
            let content = format!(
                "# Velocity Router configuration\n\
                 # Generated by velocity-ide login\n\
                 \n\
                 base_url = \"{}\"\n\
                 api_key = \"{}\"\n",
                self.base_url, self.api_key
            );
            std::fs::write(&config_path, content)
                .context("failed to write ~/.velocity/config.toml")?;
            Ok(())
        } else {
            anyhow::bail!("cannot determine home directory")
        }
    }
}

/// Minimal TOML key-value parser (handles simple `key = "value"` lines).
/// Skips comments, blank lines, section headers, and lines within sections.
/// Avoids pulling in the `toml` crate for this single use case.
fn parse_toml_simple(content: &str) -> HashMap<String, String> {
    let mut map = HashMap::new();
    let mut in_section = false;
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        // Section header — stop parsing top-level keys until next blank line.
        if line.starts_with('[') {
            in_section = true;
            continue;
        }
        // A new top-level key resets section tracking.
        if in_section {
            // Lines within a section are skipped.
            continue;
        }
        if let Some((key, value)) = line.split_once('=') {
            let key = key.trim().to_string();
            let value = value.trim().trim_matches('"').to_string();
            map.insert(key, value);
        }
    }
    map
}

/// Simple home directory lookup without adding a dependency.
pub fn dirs_next() -> Option<std::path::PathBuf> {
    std::env::var_os("USERPROFILE")
        .or_else(|| std::env::var_os("HOME"))
        .map(std::path::PathBuf::from)
}

// ─── API Response Types ─────────────────────────────────────────────────

#[derive(Debug, Serialize, Deserialize)]
pub struct UsageResponse {
    pub tier: String,
    pub tokens_used: u64,
    pub tokens_limit: u64,
    pub cost_usd: f64,
    pub cost_limit_usd: f64,
    pub assignments_count: u64,
    pub period: UsagePeriod,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct UsagePeriod {
    pub start: String,
    pub end: String,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct UsageDetailed {
    pub label: String,
    pub tier: String,
    pub total_assignments: u64,
    pub total_tokens: u64,
    pub total_cost_usd: f64,
    pub by_model: Vec<ModelUsage>,
    pub by_domain: Vec<DomainUsage>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct ModelUsage {
    pub model_id: String,
    pub assignments: u64,
    pub tokens: u64,
    pub cost_usd: f64,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct DomainUsage {
    pub domain: String,
    pub assignments: u64,
    pub tokens: u64,
    pub cost_usd: f64,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct RateLimitResponse {
    pub key_label: String,
    pub tier: String,
    pub rate_limit: RateLimitInfo,
    pub tokens: QuotaInfo,
    pub cost: CostInfo,
    pub billing_period: BillingPeriodInfo,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct RateLimitInfo {
    pub max_requests_per_minute: u32,
    pub resets_in_secs: u64,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct QuotaInfo {
    pub used: u64,
    pub limit: u64,
    pub quota_pct: f64,
    pub projected_monthly: u64,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct CostInfo {
    pub used_usd: f64,
    pub limit_usd: f64,
    pub quota_pct: f64,
    pub projected_monthly_usd: f64,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct BillingPeriodInfo {
    pub start: String,
    pub resets_in_days: i64,
}

#[derive(Debug, Serialize)]
pub struct AssignmentRequest {
    pub task: String,
    pub tier: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub context: Option<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub file_paths: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_cost_usd: Option<f64>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct AssignmentResponse {
    pub id: String,
    pub status: String,
    pub created_at: String,
    pub completed_at: Option<String>,
    pub assembled_output: Option<String>,
    pub cost: Option<AssignmentCost>,
    pub error: Option<String>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct AssignmentCost {
    pub total_tokens: u64,
    pub total_cost_usd: f64,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct HealthResponse {
    pub status: String,
    pub version: String,
    pub models_available: usize,
}

// ─── Transparency Types ──────────────────────────────────────────────────

/// Response from GET /v1/transparency — full routing transparency.
#[derive(Debug, Serialize, Deserialize)]
pub struct TransparencyResponse {
    pub summary: TransparencySummary,
    pub cost_flow: CostFlow,
    pub recent_routing_decisions: Vec<RoutingDecision>,
    pub model_selection_stats: Vec<ModelSelectionStat>,
    pub domain_distribution: Vec<DomainDistribution>,
    pub available_models: Vec<AvailableModel>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct TransparencySummary {
    pub total_assignments: usize,
    pub total_errors: usize,
    pub total_input_tokens: u64,
    pub total_output_tokens: u64,
    pub total_tokens: u64,
    pub total_cost_usd: f64,
    pub models_available: usize,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct CostFlow {
    pub input_tokens: u64,
    pub output_tokens: u64,
    pub input_output_ratio: f64,
    pub total_cost_usd: f64,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct RoutingDecision {
    pub timestamp: String,
    pub assignment_id: String,
    pub domain: String,
    pub model_id: String,
    pub provider: String,
    pub input_tokens: u64,
    pub output_tokens: u64,
    pub total_tokens: u64,
    pub cost_usd: f64,
    pub duration_ms: u64,
    pub success: bool,
    pub routing_rationale: Option<String>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct ModelSelectionStat {
    pub model_id: String,
    pub total_requests: u64,
    pub total_tokens: u64,
    pub total_cost_usd: f64,
    pub avg_duration_ms: u64,
    pub domains_served: HashMap<String, u64>,
    pub top_domain: Option<String>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct DomainDistribution {
    pub domain: String,
    pub requests: u64,
    pub tokens: u64,
    pub cost_usd: f64,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct AvailableModel {
    pub id: String,
    pub label: String,
    pub provider: String,
    pub tier: String,
    pub cost_input_per_mtok: f64,
    pub cost_output_per_mtok: f64,
}

// ─── TIMESERIES TYPES ────────────────────────────────────────────────────

/// Response from GET /v1/usage/timeseries.
#[derive(Debug, Serialize, Deserialize)]
pub struct TimeseriesResponse {
    pub granularity: String,
    pub range: String,
    pub buckets: Vec<TimeseriesBucket>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct TimeseriesBucket {
    pub label: String,
    pub tokens: u64,
    pub cost_usd: f64,
    pub requests: u64,
}

// ─── USAGE SUMMARY (ENHANCED) ────────────────────────────────────────────

/// Response from GET /v1/usage/summary — enhanced usage with projections.
#[derive(Debug, Serialize, Deserialize)]
pub struct UsageSummaryResponse {
    pub tier: String,
    pub tokens_used: u64,
    pub tokens_limit: u64,
    pub token_quota_pct: f64,
    pub cost_usd: f64,
    pub cost_limit_usd: f64,
    pub cost_quota_pct: f64,
    pub assignments_count: u64,
    pub projected_tokens: u64,
    pub projected_cost_usd: f64,
    pub billing_period: BillingPeriodDetail,
    pub sparkline: Vec<TimeseriesBucket>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct BillingPeriodDetail {
    pub start: String,
    pub end: String,
    pub days_remaining: i64,
}

// ─── AUDIT LOG ───────────────────────────────────────────────────────────

/// Response from GET /v1/audit-log.
#[derive(Debug, Serialize, Deserialize)]
pub struct AuditLogResponse {
    pub total: usize,
    pub entries: Vec<AuditLogEntry>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct AuditLogEntry {
    pub timestamp: String,
    pub assignment_id: String,
    pub status: String,
    pub total_tokens: u64,
    pub total_cost_usd: f64,
    pub duration_ms: u64,
    pub model_breakdown: Vec<AuditModelBreakdown>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct AuditModelBreakdown {
    pub model_id: String,
    pub provider: String,
    pub domain: Option<String>,
    pub tokens_used: u64,
    pub input_tokens: u64,
    pub output_tokens: u64,
    pub cost_usd: f64,
    pub duration_ms: u64,
    pub success: bool,
    pub routing_rationale: Option<String>,
}

// ─── ANALYTICS ───────────────────────────────────────────────────────────

/// Response from GET /v1/analytics/latency.
#[derive(Debug, Serialize, Deserialize)]
pub struct LatencyResponse {
    pub overall: LatencyPercentiles,
    pub by_model: Vec<ModelLatency>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct LatencyPercentiles {
    pub p50_ms: u64,
    pub p90_ms: u64,
    pub p95_ms: u64,
    pub p99_ms: u64,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct ModelLatency {
    pub model_id: String,
    pub p50_ms: u64,
    pub p90_ms: u64,
    pub p95_ms: u64,
    pub p99_ms: u64,
    pub request_count: u64,
}

// ─── KEY MANAGEMENT ──────────────────────────────────────────────────────

/// Response from GET /admin/keys/:hash.
#[derive(Debug, Serialize, Deserialize)]
pub struct KeyDetailResponse {
    pub hash: String,
    pub label: String,
    pub tier: String,
    pub created_at: String,
    pub tokens_used: u64,
    pub cost_usd: f64,
    pub assignments_count: u64,
    pub monthly_token_limit: u64,
    pub monthly_cost_limit_usd: f64,
}

/// Response from POST /admin/keys/:hash/rotate.
#[derive(Debug, Serialize, Deserialize)]
pub struct RotateKeyResponse {
    pub hash: String,
    pub new_key: String,
    pub old_key_revoked: bool,
}

/// Response from GET /v1/assignments/recent.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecentAssignmentsResponse {
    pub assignments: Vec<RecentAssignmentEntry>,
    pub total: u64,
}

/// A single entry in the recent assignments list.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecentAssignmentEntry {
    pub id: String,
    pub status: String,
    pub created_at: Option<String>,
    pub completed_at: Option<String>,
    pub cost_usd: Option<f64>,
    pub total_tokens: Option<u64>,
    pub subtask_count: Option<u64>,
    pub error: Option<String>,
}

/// Response from GET /v1/webhooks/stats.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebhookStatsResponse {
    pub webhooks: Vec<WebhookStatEntry>,
    pub summary: WebhookStatsSummary,
}

/// Per-webhook delivery statistics.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebhookStatEntry {
    pub webhook_id: String,
    pub delivered: u64,
    pub failed: u64,
    pub last_delivery: Option<String>,
    pub last_failure: Option<String>,
}

/// Summary of all webhook delivery stats.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebhookStatsSummary {
    pub total_webhooks: u64,
    pub total_delivered: u64,
    pub total_failed: u64,
}

/// Response from GET /v1/rate-limits.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RateLimitsResponse {
    pub tiers: HashMap<String, RateLimitTierInfo>,
    pub headers: HashMap<String, String>,
    pub webhook_events: Vec<String>,
}

/// Rate limit info for a single tier.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RateLimitTierInfo {
    pub requests_per_minute: u64,
    pub monthly_tokens: u64,
    pub monthly_cost_usd: f64,
    pub description: String,
}

/// Response from GET /v1/changelog.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChangelogResponse {
    pub versions: Vec<ChangelogVersion>,
}

/// A single version entry in the changelog.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChangelogVersion {
    pub version: String,
    pub date: String,
    pub changes: Vec<String>,
}

/// Response from GET /v1/models.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelsResponse {
    pub models: Vec<ModelEntry>,
    pub total: u64,
}

/// A single model in the catalog.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelEntry {
    pub id: String,
    pub label: String,
    pub provider: String,
    pub tier: String,
    pub cost_input_per_mtok: f64,
    pub cost_output_per_mtok: f64,
    pub domains: Vec<String>,
}

/// Response from GET /v1/echo.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EchoResponse {
    pub status: String,
    pub authorization: String,
    pub headers: serde_json::Value,
}

/// Response from POST /v1/assignments/estimate.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EstimateResponse {
    pub estimated_cost_usd: f64,
    pub estimated_tokens: u64,
    pub routing: Vec<serde_json::Value>,
}

/// Response from POST /v1/assignments/batch.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BatchResponse {
    pub results: Vec<BatchResultEntry>,
    pub total_tasks: u64,
    pub total_tokens: u64,
    pub total_cost_usd: f64,
}

/// A single result entry in a batch response.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BatchResultEntry {
    pub index: u64,
    pub assignment_id: String,
    pub status: String,
    pub subtask_count: u64,
    pub tokens_used: u64,
    pub cost_usd: f64,
    pub results: Vec<serde_json::Value>,
}

/// Response from GET /v1/usage/billing.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BillingResponse {
    pub period: serde_json::Value,
    pub usage: serde_json::Value,
    pub limits: serde_json::Value,
}

/// Response from GET /v1/analytics.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnalyticsResponse {
    pub total_assignments: u64,
    pub total_tokens: u64,
    pub total_cost_usd: f64,
    pub success_rate: f64,
    pub avg_duration_ms: f64,
}

/// Response from GET /health/providers.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderHealthResponse {
    pub providers: Vec<ProviderStatus>,
}

/// Status of a single provider.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderStatus {
    pub provider: String,
    pub state: String,
    pub consecutive_failures: u64,
    pub consecutive_successes: u64,
}

// ─── Client ─────────────────────────────────────────────────────────────

/// Synchronous HTTP client for the Velocity Router API.
pub struct VelocityClient {
    config: VelocityConfig,
    agent: ureq::Agent,
    retry_config: RetryConfig,
}

/// Retry configuration for HTTP requests.
#[derive(Debug, Clone)]
pub struct RetryConfig {
    /// Maximum number of retry attempts (not counting the initial request).
    pub max_retries: u32,
    /// Initial backoff duration.
    pub initial_backoff_ms: u64,
    /// Maximum backoff duration.
    pub max_backoff_ms: u64,
    /// Whether to add random jitter to backoff (avoids thundering herd).
    pub jitter: bool,
}

impl Default for RetryConfig {
    fn default() -> Self {
        Self {
            max_retries: 3,
            initial_backoff_ms: 200,
            max_backoff_ms: 5000,
            jitter: true,
        }
    }
}

impl VelocityClient {
    pub fn new(config: VelocityConfig) -> Self {
        let agent = ureq::AgentBuilder::new()
            .timeout_connect(Duration::from_secs(5))
            .timeout_read(Duration::from_secs(30))
            .timeout_write(Duration::from_secs(10))
            .build();
        Self {
            config,
            agent,
            retry_config: RetryConfig::default(),
        }
    }

    pub fn from_env() -> Result<Self> {
        let config = VelocityConfig::load()?;
        Ok(Self::new(config))
    }

    /// Set custom retry configuration.
    pub fn with_retry_config(mut self, config: RetryConfig) -> Self {
        self.retry_config = config;
        self
    }

    fn auth_header(&self) -> String {
        format!("Bearer {}", self.config.api_key)
    }

    fn url(&self, path: &str) -> String {
        format!("{}{}", self.config.base_url.trim_end_matches('/'), path)
    }

    /// Compute backoff duration with optional jitter.
    fn backoff_duration(&self, base_ms: u64) -> Duration {
        let ms = if self.retry_config.jitter {
            // Add ±25% random jitter to avoid thundering herd.
            let jitter_range = base_ms / 4;
            let jitter = if jitter_range > 0 {
                (rand::random::<u64>() % (jitter_range * 2)).saturating_sub(jitter_range)
            } else {
                0
            };
            base_ms.saturating_add_signed(jitter as i64)
        } else {
            base_ms
        };
        Duration::from_millis(ms.min(self.retry_config.max_backoff_ms))
    }

    /// Execute a GET request with exponential backoff retry.
    /// Retries on 5xx errors and transport failures.
    fn get_with_retry(&self, url: &str, auth: bool) -> Result<ureq::Response> {
        let mut last_error = None;
        let mut backoff = self.retry_config.initial_backoff_ms;

        for attempt in 0..=self.retry_config.max_retries {
            let mut req = self.agent.get(url);
            if auth {
                req = req.set("Authorization", &self.auth_header());
            }

            match req.call() {
                Ok(resp) => return Ok(resp),
                Err(ureq::Error::Status(code, _resp)) if code >= 500 => {
                    last_error = Some(anyhow::anyhow!("server error: HTTP {}", code));
                    if attempt < self.retry_config.max_retries {
                        std::thread::sleep(self.backoff_duration(backoff));
                        backoff = (backoff * 2).min(self.retry_config.max_backoff_ms);
                    }
                }
                Err(ureq::Error::Transport(_)) => {
                    last_error = Some(anyhow::anyhow!("transport error (connection failed)"));
                    if attempt < self.retry_config.max_retries {
                        std::thread::sleep(self.backoff_duration(backoff));
                        backoff = (backoff * 2).min(self.retry_config.max_backoff_ms);
                    }
                }
                Err(e) => return Err(anyhow::anyhow!("{}", e)),
            }
        }

        Err(last_error.unwrap_or_else(|| anyhow::anyhow!("max retries exceeded")))
    }

    /// GET /health — check if the router is reachable.
    pub fn health(&self) -> Result<HealthResponse> {
        let resp = self
            .get_with_retry(&self.url("/health"), false)
            .context("failed to reach velocity router")?;
        resp.into_json()
            .context("failed to parse health response")
    }

    /// GET /v1/usage — current usage summary.
    pub fn get_usage(&self) -> Result<UsageResponse> {
        let resp = self
            .get_with_retry(&self.url("/v1/usage"), true)
            .context("failed to fetch usage")?;
        resp.into_json()
            .context("failed to parse usage response")
    }

    /// GET /v1/usage/summary — enhanced usage with projections and sparkline.
    pub fn get_usage_summary(&self) -> Result<UsageSummaryResponse> {
        let resp = self
            .get_with_retry(&self.url("/v1/usage/summary"), true)
            .context("failed to fetch usage summary")?;
        resp.into_json()
            .context("failed to parse usage summary response")
    }

    /// GET /v1/usage/detailed — per-model and per-domain breakdown.
    pub fn get_usage_detailed(&self) -> Result<UsageDetailed> {
        let resp = self
            .get_with_retry(&self.url("/v1/usage/detailed"), true)
            .context("failed to fetch detailed usage")?;
        resp.into_json()
            .context("failed to parse detailed usage response")
    }

    /// GET /v1/usage/rate-limit — rate limit and quota status.
    pub fn get_rate_limit(&self) -> Result<RateLimitResponse> {
        let resp = self
            .get_with_retry(&self.url("/v1/usage/rate-limit"), true)
            .context("failed to fetch rate limit status")?;
        resp.into_json()
            .context("failed to parse rate limit response")
    }

    /// GET /v1/usage/timeseries — time-series usage data.
    /// `granularity`: "hourly" or "daily".
    /// `range`: "6h", "12h", "24h", "48h", "7d", "30d", "90d".
    pub fn get_timeseries(&self, granularity: &str, range: &str) -> Result<TimeseriesResponse> {
        let url = format!(
            "{}/v1/usage/timeseries?granularity={}&range={}",
            self.config.base_url.trim_end_matches('/'),
            granularity,
            range
        );
        let resp = self
            .get_with_retry(&url, true)
            .context("failed to fetch timeseries")?;
        resp.into_json()
            .context("failed to parse timeseries response")
    }

    /// GET /v1/transparency — full routing transparency data.
    pub fn get_transparency(&self) -> Result<TransparencyResponse> {
        let resp = self
            .get_with_retry(&self.url("/v1/transparency"), true)
            .context("failed to fetch transparency data")?;
        resp.into_json()
            .context("failed to parse transparency response")
    }

    /// GET /v1/audit-log — paginated audit trail.
    pub fn get_audit_log(&self) -> Result<AuditLogResponse> {
        let resp = self
            .get_with_retry(&self.url("/v1/audit-log"), true)
            .context("failed to fetch audit log")?;
        resp.into_json()
            .context("failed to parse audit log response")
    }

    /// GET /v1/analytics/latency — latency percentiles.
    pub fn get_latency(&self) -> Result<LatencyResponse> {
        let resp = self
            .get_with_retry(&self.url("/v1/analytics/latency"), true)
            .context("failed to fetch latency analytics")?;
        resp.into_json()
            .context("failed to parse latency response")
    }

    /// GET /admin/keys/:hash — key detail (admin only).
    pub fn get_key_detail(&self, hash: &str) -> Result<KeyDetailResponse> {
        let resp = self
            .get_with_retry(&self.url(&format!("/admin/keys/{}", hash)), true)
            .context("failed to fetch key detail")?;
        resp.into_json()
            .context("failed to parse key detail response")
    }

    /// POST /admin/keys/:hash/rotate — rotate an API key (admin only).
    pub fn rotate_key(&self, hash: &str) -> Result<RotateKeyResponse> {
        let resp = self
            .agent
            .post(&self.url(&format!("/admin/keys/{}/rotate", hash)))
            .set("Authorization", &self.auth_header())
            .call()
            .context("failed to rotate key")?;
        resp.into_json()
            .context("failed to parse rotate key response")
    }

    /// POST /v1/assignments — submit a task for orchestration.
    pub fn submit_assignment(&self, req: &AssignmentRequest) -> Result<AssignmentResponse> {
        let resp = self
            .agent
            .post(&self.url("/v1/assignments"))
            .set("Authorization", &self.auth_header())
            .set("Content-Type", "application/json")
            .send_json(serde_json::to_value(req)?)
            .context("failed to submit assignment")?;
        resp.into_json()
            .context("failed to parse assignment response")
    }

    /// GET /v1/assignments/:id — poll assignment status.
    pub fn get_assignment(&self, id: &str) -> Result<AssignmentResponse> {
        let resp = self
            .get_with_retry(&self.url(&format!("/v1/assignments/{}", id)), true)
            .context("failed to fetch assignment")?;
        resp.into_json()
            .context("failed to parse assignment response")
    }

    /// GET /v1/assignments/recent — list recent assignments (max 50, newest first).
    pub fn get_recent_assignments(&self) -> Result<RecentAssignmentsResponse> {
        let resp = self
            .get_with_retry(&self.url("/v1/assignments/recent"), true)
            .context("failed to fetch recent assignments")?;
        resp.into_json()
            .context("failed to parse recent assignments response")
    }

    /// GET /v1/webhooks/stats — webhook delivery statistics.
    pub fn get_webhook_stats(&self) -> Result<WebhookStatsResponse> {
        let resp = self
            .get_with_retry(&self.url("/v1/webhooks/stats"), true)
            .context("failed to fetch webhook stats")?;
        resp.into_json()
            .context("failed to parse webhook stats response")
    }

    /// GET /v1/rate-limits — public rate limit configuration per tier.
    pub fn get_rate_limits(&self) -> Result<RateLimitsResponse> {
        let resp = self
            .get_with_retry(&self.url("/v1/rate-limits"), false)
            .context("failed to fetch rate limits")?;
        resp.into_json()
            .context("failed to parse rate limits response")
    }

    /// GET /v1/changelog — version history.
    pub fn get_changelog(&self) -> Result<ChangelogResponse> {
        let resp = self
            .get_with_retry(&self.url("/v1/changelog"), false)
            .context("failed to fetch changelog")?;
        resp.into_json()
            .context("failed to parse changelog response")
    }

    /// GET /v1/models — public model catalog.
    pub fn get_models(&self) -> Result<ModelsResponse> {
        let resp = self
            .get_with_retry(&self.url("/v1/models"), false)
            .context("failed to fetch models catalog")?;
        resp.into_json()
            .context("failed to parse models response")
    }

    /// GET /v1/echo — connectivity test (returns status + masked auth).
    pub fn echo(&self) -> Result<EchoResponse> {
        let resp = self
            .get_with_retry(&self.url("/v1/echo"), true)
            .context("failed to reach echo endpoint")?;
        resp.into_json()
            .context("failed to parse echo response")
    }

    /// POST /v1/assignments/estimate — estimate cost and routing without executing.
    pub fn estimate_assignment(&self, req: &AssignmentRequest) -> Result<EstimateResponse> {
        let resp = self
            .agent
            .post(&self.url("/v1/assignments/estimate"))
            .set("Authorization", &self.auth_header())
            .set("Content-Type", "application/json")
            .send_json(serde_json::to_value(req)?)
            .context("failed to estimate assignment")?;
        resp.into_json()
            .context("failed to parse estimate response")
    }

    /// POST /v1/assignments/batch — submit multiple tasks at once.
    pub fn submit_batch(&self, tasks: &[AssignmentRequest], tier: &str) -> Result<BatchResponse> {
        let body = serde_json::json!({
            "tasks": tasks.iter().map(|t| serde_json::to_value(t).unwrap()).collect::<Vec<_>>(),
            "tier": tier,
        });
        let resp = self
            .agent
            .post(&self.url("/v1/assignments/batch"))
            .set("Authorization", &self.auth_header())
            .set("Content-Type", "application/json")
            .send_json(body)
            .context("failed to submit batch assignment")?;
        resp.into_json()
            .context("failed to parse batch response")
    }

    /// GET /v1/usage/billing — billing period summary.
    pub fn get_billing(&self) -> Result<BillingResponse> {
        let resp = self
            .get_with_retry(&self.url("/v1/usage/billing"), true)
            .context("failed to fetch billing data")?;
        resp.into_json()
            .context("failed to parse billing response")
    }

    /// GET /v1/analytics — usage analytics summary.
    pub fn get_analytics(&self) -> Result<AnalyticsResponse> {
        let resp = self
            .get_with_retry(&self.url("/v1/analytics"), true)
            .context("failed to fetch analytics")?;
        resp.into_json()
            .context("failed to parse analytics response")
    }

    /// GET /health/providers — provider circuit breaker status.
    pub fn get_provider_health(&self) -> Result<ProviderHealthResponse> {
        let resp = self
            .get_with_retry(&self.url("/health/providers"), false)
            .context("failed to fetch provider health")?;
        resp.into_json()
            .context("failed to parse provider health response")
    }
}

// ─── Formatting Helpers ─────────────────────────────────────────────────

/// Format a number with thousands separators.
pub fn fmt_number(n: u64) -> String {
    let s = n.to_string();
    let mut result = String::new();
    for (i, c) in s.chars().rev().enumerate() {
        if i > 0 && i % 3 == 0 {
            result.push(',');
        }
        result.push(c);
    }
    result.chars().rev().collect()
}

/// Format a USD amount.
pub fn fmt_currency(n: f64) -> String {
    if n == 0.0 {
        "$0.00".to_string()
    } else if n < 0.01 {
        format!("${:.4}", n)
    } else {
        format!("${:.2}", n)
    }
}

/// Format a percentage.
pub fn fmt_percent(n: f64) -> String {
    format!("{:.1}%", n)
}

// ─── Diagnostics & Validation ────────────────────────────────────────────────

/// Diagnostic info about the VelocityConfig connection.
#[derive(Debug, Clone, Serialize)]
pub struct ConnectionInfo {
    pub base_url: String,
    pub api_key_prefix: String,
    pub api_key_length: usize,
    pub is_https: bool,
    pub validation_issues: Vec<String>,
}

impl VelocityConfig {
    /// Return diagnostic info about the connection configuration.
    pub fn connection_info(&self) -> ConnectionInfo {
        let prefix = if self.api_key.len() >= 8 {
            format!("{}...", &self.api_key[..8])
        } else {
            "***".to_string()
        };
        let is_https = self.base_url.starts_with("https://");
        let mut issues = Vec::new();
        if self.base_url.is_empty() {
            issues.push("base_url is empty".to_string());
        }
        if !self.base_url.starts_with("http://") && !self.base_url.starts_with("https://") {
            issues.push("base_url must start with http:// or https://".to_string());
        }
        if self.api_key.is_empty() {
            issues.push("api_key is empty".to_string());
        }
        if self.api_key.len() < 10 {
            issues.push("api_key seems too short (< 10 chars)".to_string());
        }
        ConnectionInfo {
            base_url: self.base_url.clone(),
            api_key_prefix: prefix,
            api_key_length: self.api_key.len(),
            is_https,
            validation_issues: issues,
        }
    }

    /// Validate the configuration. Returns warnings (empty = clean).
    pub fn validate(&self) -> Vec<String> {
        self.connection_info().validation_issues
    }
}

/// Diagnostic snapshot of retry configuration.
#[derive(Debug, Clone, Serialize)]
pub struct RetryConfigInfo {
    pub max_retries: u32,
    pub initial_backoff_ms: u64,
    pub max_backoff_ms: u64,
    pub jitter_enabled: bool,
    pub max_possible_delay_ms: u64,
    pub validation_issues: Vec<String>,
}

impl RetryConfig {
    /// Return a diagnostic snapshot of the retry configuration.
    pub fn info(&self) -> RetryConfigInfo {
        // Max delay: initial * 2^max_retries, capped at max_backoff.
        let max_delay = (self.initial_backoff_ms * (1u64 << self.max_retries.min(20)))
            .min(self.max_backoff_ms);
        let mut issues = Vec::new();
        if self.max_retries == 0 {
            issues.push("max_retries is 0: no retries will be attempted".to_string());
        }
        if self.initial_backoff_ms == 0 {
            issues.push("initial_backoff_ms is 0: immediate retries".to_string());
        }
        if self.max_backoff_ms < self.initial_backoff_ms {
            issues.push(format!(
                "max_backoff_ms ({}) < initial_backoff_ms ({})",
                self.max_backoff_ms, self.initial_backoff_ms
            ));
        }
        RetryConfigInfo {
            max_retries: self.max_retries,
            initial_backoff_ms: self.initial_backoff_ms,
            max_backoff_ms: self.max_backoff_ms,
            jitter_enabled: self.jitter,
            max_possible_delay_ms: max_delay,
            validation_issues: issues,
        }
    }
}

/// Diagnostic snapshot of the client's connection state.
#[derive(Debug, Clone, Serialize)]
pub struct ClientDiagnostics {
    pub connection: ConnectionInfo,
    pub retry: RetryConfigInfo,
}

impl VelocityClient {
    /// Return a diagnostic snapshot of the client's configuration.
    pub fn diagnostics(&self) -> ClientDiagnostics {
        ClientDiagnostics {
            connection: self.config.connection_info(),
            retry: self.retry_config.info(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fmt_number_works() {
        assert_eq!(fmt_number(0), "0");
        assert_eq!(fmt_number(999), "999");
        assert_eq!(fmt_number(1000), "1,000");
        assert_eq!(fmt_number(1234567), "1,234,567");
    }

    #[test]
    fn fmt_currency_works() {
        assert_eq!(fmt_currency(0.0), "$0.00");
        assert_eq!(fmt_currency(0.0034), "$0.0034");
        assert_eq!(fmt_currency(1.5), "$1.50");
        assert_eq!(fmt_currency(123.456), "$123.46");
    }

    #[test]
    fn fmt_percent_works() {
        assert_eq!(fmt_percent(0.0), "0.0%");
        assert_eq!(fmt_percent(42.567), "42.6%");
        assert_eq!(fmt_percent(100.0), "100.0%");
    }

    #[test]
    fn config_load_from_env() {
        // Use unique prefixed env vars to avoid races with other tests.
        std::env::set_var("VELOCITY_BASE_URL", "http://test:8787");
        std::env::set_var("VELOCITY_API_KEY", "vr_test_key");
        let config = VelocityConfig::load().unwrap();
        assert_eq!(config.base_url, "http://test:8787");
        assert_eq!(config.api_key, "vr_test_key");
        // Clean up.
        std::env::remove_var("VELOCITY_BASE_URL");
        std::env::remove_var("VELOCITY_API_KEY");
        // After removing, load() should fail.
        assert!(VelocityConfig::load().is_err());
    }

    #[test]
    fn parse_toml_simple_works() {
        let content = r#"
# This is a comment
base_url = "http://localhost:8787"
api_key = "vr_standard_abc123"

[section]
ignored = true
"#;
        let parsed = parse_toml_simple(content);
        assert_eq!(parsed.get("base_url").unwrap(), "http://localhost:8787");
        assert_eq!(parsed.get("api_key").unwrap(), "vr_standard_abc123");
        // Section headers and their contents are skipped.
        assert!(parsed.get("section").is_none());
        assert!(parsed.get("ignored").is_none());
    }

    #[test]
    fn parse_toml_handles_comments_and_blanks() {
        let content = "# comment\n\nkey1 = \"val1\"\n  key2 = \"val2\"  \n";
        let parsed = parse_toml_simple(content);
        assert_eq!(parsed.get("key1").unwrap(), "val1");
        assert_eq!(parsed.get("key2").unwrap(), "val2");
    }

    #[test]
    fn retry_config_default_has_jitter() {
        let cfg = RetryConfig::default();
        assert!(cfg.jitter);
        assert_eq!(cfg.max_retries, 3);
        assert_eq!(cfg.initial_backoff_ms, 200);
        assert_eq!(cfg.max_backoff_ms, 5000);
    }

    #[test]
    fn backoff_duration_respects_max() {
        let client = VelocityClient::new(VelocityConfig {
            base_url: "http://localhost:8787".into(),
            api_key: "test".into(),
        });
        // Even with a huge base, should not exceed max_backoff_ms.
        let d = client.backoff_duration(999_999);
        assert!(d.as_millis() <= 5000);
    }

    #[test]
    fn backoff_without_jitter_is_deterministic() {
        let cfg = VelocityConfig {
            base_url: "http://localhost:8787".into(),
            api_key: "test".into(),
        };
        let client = VelocityClient::new(cfg).with_retry_config(RetryConfig {
            jitter: false,
            ..RetryConfig::default()
        });
        let d1 = client.backoff_duration(1000);
        let d2 = client.backoff_duration(1000);
        assert_eq!(d1, d2);
    }

    #[test]
    fn transparency_response_deserializes() {
        let json = r#"{
            "summary": {
                "total_assignments": 42,
                "total_errors": 1,
                "total_input_tokens": 100000,
                "total_output_tokens": 50000,
                "total_tokens": 150000,
                "total_cost_usd": 0.15,
                "models_available": 12
            },
            "cost_flow": {
                "input_tokens": 100000,
                "output_tokens": 50000,
                "input_output_ratio": 2.0,
                "total_cost_usd": 0.15
            },
            "recent_routing_decisions": [],
            "model_selection_stats": [],
            "domain_distribution": [],
            "available_models": []
        }"#;
        let resp: TransparencyResponse = serde_json::from_str(json).unwrap();
        assert_eq!(resp.summary.total_assignments, 42);
        assert_eq!(resp.cost_flow.input_output_ratio, 2.0);
        assert_eq!(resp.summary.models_available, 12);
    }

    #[test]
    fn timeseries_response_deserializes() {
        let json = r#"{
            "granularity": "hourly",
            "range": "24h",
            "buckets": [
                {"label": "14:00", "tokens": 1200, "cost_usd": 0.001, "requests": 3}
            ]
        }"#;
        let resp: TimeseriesResponse = serde_json::from_str(json).unwrap();
        assert_eq!(resp.granularity, "hourly");
        assert_eq!(resp.buckets.len(), 1);
        assert_eq!(resp.buckets[0].tokens, 1200);
    }

    #[test]
    fn audit_log_response_deserializes() {
        let json = r#"{
            "total": 1,
            "entries": [{
                "timestamp": "2026-08-23T12:00:00Z",
                "assignment_id": "abc-123",
                "status": "completed",
                "total_tokens": 5000,
                "total_cost_usd": 0.005,
                "duration_ms": 1500,
                "model_breakdown": [{
                    "model_id": "gpt-4o",
                    "provider": "openai",
                    "domain": "gui_design",
                    "tokens_used": 5000,
                    "input_tokens": 3000,
                    "output_tokens": 2000,
                    "cost_usd": 0.005,
                    "duration_ms": 1500,
                    "success": true,
                    "routing_rationale": "Best for GUI tasks"
                }]
            }]
        }"#;
        let resp: AuditLogResponse = serde_json::from_str(json).unwrap();
        assert_eq!(resp.total, 1);
        assert_eq!(resp.entries[0].model_breakdown[0].input_tokens, 3000);
        assert_eq!(resp.entries[0].model_breakdown[0].success, true);
    }

    #[test]
    fn latency_response_deserializes() {
        let json = r#"{
            "overall": {"p50_ms": 200, "p90_ms": 800, "p95_ms": 1200, "p99_ms": 3000},
            "by_model": [{
                "model_id": "gpt-4o",
                "p50_ms": 150, "p90_ms": 600, "p95_ms": 900, "p99_ms": 2500,
                "request_count": 100
            }]
        }"#;
        let resp: LatencyResponse = serde_json::from_str(json).unwrap();
        assert_eq!(resp.overall.p50_ms, 200);
        assert_eq!(resp.by_model.len(), 1);
    }

    // ─── Diagnostics & Validation Tests ──────────────────────────────────────

    #[test]
    fn connection_info_valid_config() {
        let cfg = VelocityConfig {
            base_url: "https://router.velocity.io".into(),
            api_key: "vr_standard_abcdef1234567890".into(),
        };
        let info = cfg.connection_info();
        assert!(info.is_https);
        assert_eq!(info.api_key_prefix, "vr_stand...");
        assert_eq!(info.api_key_length, 28);
        assert!(info.validation_issues.is_empty());
    }

    #[test]
    fn connection_info_empty_url() {
        let cfg = VelocityConfig {
            base_url: "".into(),
            api_key: "vr_standard_abcdef1234567890".into(),
        };
        let info = cfg.connection_info();
        assert!(info.validation_issues.iter().any(|i| i.contains("base_url is empty")));
        assert!(!info.is_https);
    }

    #[test]
    fn connection_info_short_key() {
        let cfg = VelocityConfig {
            base_url: "http://localhost:8787".into(),
            api_key: "abc".into(),
        };
        let info = cfg.connection_info();
        assert!(info.validation_issues.iter().any(|i| i.contains("too short")));
        assert_eq!(info.api_key_prefix, "***");
    }

    #[test]
    fn connection_info_empty_key() {
        let cfg = VelocityConfig {
            base_url: "http://localhost:8787".into(),
            api_key: "".into(),
        };
        let info = cfg.connection_info();
        assert!(info.validation_issues.iter().any(|i| i.contains("api_key is empty")));
        assert!(info.validation_issues.iter().any(|i| i.contains("too short")));
    }

    #[test]
    fn connection_info_https_detection() {
        let http = VelocityConfig {
            base_url: "http://localhost:8787".into(),
            api_key: "vr_standard_1234567890".into(),
        };
        assert!(!http.connection_info().is_https);

        let https = VelocityConfig {
            base_url: "https://router.velocity.io".into(),
            api_key: "vr_standard_1234567890".into(),
        };
        assert!(https.connection_info().is_https);
    }

    #[test]
    fn connection_info_bad_scheme() {
        let cfg = VelocityConfig {
            base_url: "ftp://example.com".into(),
            api_key: "vr_standard_1234567890".into(),
        };
        let info = cfg.connection_info();
        assert!(info.validation_issues.iter().any(|i| i.contains("http://")));
    }

    #[test]
    fn validate_delegates_to_connection_info() {
        let cfg = VelocityConfig {
            base_url: "".into(),
            api_key: "".into(),
        };
        let warnings = cfg.validate();
        assert!(warnings.len() >= 2);
    }

    #[test]
    fn retry_config_info_default() {
        let info = RetryConfig::default().info();
        assert_eq!(info.max_retries, 3);
        assert_eq!(info.initial_backoff_ms, 200);
        assert_eq!(info.max_backoff_ms, 5000);
        assert!(info.jitter_enabled);
        assert!(info.validation_issues.is_empty());
        // Max delay: 200 * 2^3 = 1600, capped at 5000 → 1600.
        assert_eq!(info.max_possible_delay_ms, 1600);
    }

    #[test]
    fn retry_config_info_zero_retries() {
        let cfg = RetryConfig {
            max_retries: 0,
            ..RetryConfig::default()
        };
        let info = cfg.info();
        assert!(info.validation_issues.iter().any(|i| i.contains("max_retries is 0")));
    }

    #[test]
    fn retry_config_info_zero_backoff() {
        let cfg = RetryConfig {
            initial_backoff_ms: 0,
            ..RetryConfig::default()
        };
        let info = cfg.info();
        assert!(info.validation_issues.iter().any(|i| i.contains("initial_backoff_ms is 0")));
    }

    #[test]
    fn retry_config_info_bad_backoff_ordering() {
        let cfg = RetryConfig {
            initial_backoff_ms: 1000,
            max_backoff_ms: 500,
            ..RetryConfig::default()
        };
        let info = cfg.info();
        assert!(info.validation_issues.iter().any(|i| i.contains("max_backoff_ms")));
    }

    #[test]
    fn client_diagnostics_serializes() {
        let client = VelocityClient::new(VelocityConfig {
            base_url: "https://router.velocity.io".into(),
            api_key: "vr_standard_abcdef1234567890".into(),
        });
        let diag = client.diagnostics();
        let json = serde_json::to_string(&diag).unwrap();
        assert!(json.contains("connection"));
        assert!(json.contains("retry"));
        assert!(json.contains("router.velocity.io"));
        // API key prefix should be masked in the output.
        assert!(json.contains("vr_stand..."));
        assert!(!json.contains("vr_standard_abcdef1234567890"));
    }

    #[test]
    fn client_diagnostics_with_custom_retry() {
        let client = VelocityClient::new(VelocityConfig {
            base_url: "http://localhost:8787".into(),
            api_key: "vr_standard_1234567890".into(),
        })
        .with_retry_config(RetryConfig {
            max_retries: 5,
            initial_backoff_ms: 100,
            max_backoff_ms: 10000,
            jitter: false,
        });
        let diag = client.diagnostics();
        assert_eq!(diag.retry.max_retries, 5);
        assert!(!diag.retry.jitter_enabled);
        assert!(diag.retry.validation_issues.is_empty());
    }

    // ─── fmt_number Edge Cases ──────────────────────────────────────────────

    #[test]
    fn fmt_number_large_values() {
        assert_eq!(fmt_number(1_000_000_000), "1,000,000,000");
        assert_eq!(fmt_number(99_999_999), "99,999,999");
        assert_eq!(fmt_number(10_000), "10,000");
        assert_eq!(fmt_number(100_000), "100,000");
    }

    #[test]
    fn fmt_number_single_digits() {
        for i in 0..10 {
            assert_eq!(fmt_number(i), i.to_string());
        }
    }

    #[test]
    fn fmt_number_boundary_values() {
        assert_eq!(fmt_number(999), "999");
        assert_eq!(fmt_number(1000), "1,000");
        assert_eq!(fmt_number(999_999), "999,999");
        assert_eq!(fmt_number(1_000_000), "1,000,000");
    }

    // ─── fmt_currency Edge Cases ────────────────────────────────────────────

    #[test]
    fn fmt_currency_boundary_at_one_cent() {
        // Exactly $0.01 should use 2 decimal places.
        assert_eq!(fmt_currency(0.01), "$0.01");
        // Just below $0.01 should use 4 decimal places.
        assert_eq!(fmt_currency(0.0099), "$0.0099");
    }

    #[test]
    fn fmt_currency_large_amounts() {
        assert_eq!(fmt_currency(999_999.99), "$999999.99");
        assert_eq!(fmt_currency(1_234_567.89), "$1234567.89");
    }

    #[test]
    fn fmt_currency_rounding() {
        // 0.005 < 0.01 → 4-decimal format.
        assert_eq!(fmt_currency(0.005), "$0.0050");
        // 0.004 < 0.01 → 4-decimal format.
        assert_eq!(fmt_currency(0.004), "$0.0040");
    }

    // ─── fmt_percent Edge Cases ─────────────────────────────────────────────

    #[test]
    fn fmt_percent_negative_and_over_hundred() {
        assert_eq!(fmt_percent(-5.0), "-5.0%");
        assert_eq!(fmt_percent(150.0), "150.0%");
        assert_eq!(fmt_percent(99.99), "100.0%");
    }

    // ─── parse_toml Edge Cases ──────────────────────────────────────────────

    #[test]
    fn parse_toml_empty_content() {
        let parsed = parse_toml_simple("");
        assert!(parsed.is_empty());
    }

    #[test]
    fn parse_toml_only_comments() {
        let content = "# comment 1\n# comment 2\n";
        let parsed = parse_toml_simple(content);
        assert!(parsed.is_empty());
    }

    #[test]
    fn parse_toml_value_with_equals_sign() {
        // Values containing '=' should be preserved (split_once splits on first '=').
        let content = r#"key = "val=ue""#;
        let parsed = parse_toml_simple(content);
        assert_eq!(parsed.get("key").unwrap(), "val=ue");
    }

    #[test]
    fn parse_toml_keys_after_section_are_skipped() {
        let content = r#"
before = "yes"
[section]
inside = "no"
after_section = "also no"
"#;
        let parsed = parse_toml_simple(content);
        assert_eq!(parsed.get("before").unwrap(), "yes");
        assert!(parsed.get("inside").is_none());
        assert!(parsed.get("after_section").is_none());
    }

    #[test]
    fn parse_toml_missing_key() {
        let content = r#"base_url = "http://localhost:8787""#;
        let parsed = parse_toml_simple(content);
        assert!(parsed.get("nonexistent").is_none());
        assert!(parsed.get("base_url").is_some());
    }

    // ─── URL Builder ────────────────────────────────────────────────────────

    #[test]
    fn url_builder_strips_trailing_slash() {
        let client = VelocityClient::new(VelocityConfig {
            base_url: "http://localhost:8787/".into(),
            api_key: "vr_test_key".into(),
        });
        assert_eq!(client.url("/health"), "http://localhost:8787/health");
    }

    #[test]
    fn url_builder_no_trailing_slash() {
        let client = VelocityClient::new(VelocityConfig {
            base_url: "http://localhost:8787".into(),
            api_key: "vr_test_key".into(),
        });
        assert_eq!(client.url("/v1/usage"), "http://localhost:8787/v1/usage");
    }

    #[test]
    fn auth_header_format() {
        let client = VelocityClient::new(VelocityConfig {
            base_url: "http://localhost:8787".into(),
            api_key: "vr_standard_abc123".into(),
        });
        assert_eq!(client.auth_header(), "Bearer vr_standard_abc123");
    }

    // ─── Connection Info Additional ─────────────────────────────────────────

    #[test]
    fn connection_info_vr_admin_prefix() {
        let cfg = VelocityConfig {
            base_url: "https://router.velocity.io".into(),
            api_key: "vr_admin_abcdef1234567890".into(),
        };
        let info = cfg.connection_info();
        assert_eq!(info.api_key_prefix, "vr_admin...");
        assert!(info.validation_issues.is_empty());
    }

    #[test]
    fn connection_info_key_exactly_8_chars() {
        let cfg = VelocityConfig {
            base_url: "http://localhost:8787".into(),
            api_key: "12345678".into(),
        };
        let info = cfg.connection_info();
        assert_eq!(info.api_key_prefix, "12345678...");
        assert_eq!(info.api_key_length, 8);
        // 8 chars >= 8, so prefix is shown, but < 10 triggers short warning.
        assert!(info.validation_issues.iter().any(|i| i.contains("too short")));
    }

    #[test]
    fn connection_info_key_7_chars_shows_mask() {
        let cfg = VelocityConfig {
            base_url: "http://localhost:8787".into(),
            api_key: "1234567".into(),
        };
        let info = cfg.connection_info();
        assert_eq!(info.api_key_prefix, "***");
    }

    #[test]
    fn connection_info_multiple_issues() {
        let cfg = VelocityConfig {
            base_url: "".into(),
            api_key: "".into(),
        };
        let info = cfg.connection_info();
        // Should have: empty base_url, bad scheme, empty key, short key.
        assert!(info.validation_issues.len() >= 3);
    }

    // ─── Backoff Duration ───────────────────────────────────────────────────

    #[test]
    fn backoff_duration_attempt_zero_no_jitter() {
        let client = VelocityClient::new(VelocityConfig {
            base_url: "http://localhost:8787".into(),
            api_key: "test".into(),
        })
        .with_retry_config(RetryConfig {
            jitter: false,
            ..RetryConfig::default()
        });
        // With no jitter, backoff_duration(200) = 200ms.
        let d = client.backoff_duration(200);
        assert_eq!(d.as_millis(), 200);
    }

    #[test]
    fn backoff_duration_with_jitter_stays_in_range() {
        let client = VelocityClient::new(VelocityConfig {
            base_url: "http://localhost:8787".into(),
            api_key: "test".into(),
        })
        .with_retry_config(RetryConfig {
            jitter: true,
            initial_backoff_ms: 1000,
            max_backoff_ms: 50000,
            ..RetryConfig::default()
        });
        // With base=1000, jitter is ±250 → range [750, 1250].
        for _ in 0..50 {
            let d = client.backoff_duration(1000);
            let ms = d.as_millis();
            assert!(ms >= 750 && ms <= 1250, "jitter out of range: {ms}");
        }
    }

    #[test]
    fn backoff_duration_zero_base_with_jitter() {
        let client = VelocityClient::new(VelocityConfig {
            base_url: "http://localhost:8787".into(),
            api_key: "test".into(),
        })
        .with_retry_config(RetryConfig {
            jitter: true,
            ..RetryConfig::default()
        });
        // base=0 → jitter_range=0 → no jitter → 0ms.
        let d = client.backoff_duration(0);
        assert_eq!(d.as_millis(), 0);
    }

    // ─── RetryConfig Info ───────────────────────────────────────────────────

    #[test]
    fn retry_config_max_delay_calculation() {
        // initial=100, max_retries=4 → 100 * 2^4 = 1600, capped at max=10000 → 1600.
        let cfg = RetryConfig {
            max_retries: 4,
            initial_backoff_ms: 100,
            max_backoff_ms: 10000,
            jitter: true,
        };
        let info = cfg.info();
        assert_eq!(info.max_possible_delay_ms, 1600);
    }

    #[test]
    fn retry_config_max_delay_capped() {
        // initial=1000, max_retries=10 → 1000 * 2^10 = 1_024_000, capped at max=5000 → 5000.
        let cfg = RetryConfig {
            max_retries: 10,
            initial_backoff_ms: 1000,
            max_backoff_ms: 5000,
            jitter: false,
        };
        let info = cfg.info();
        assert_eq!(info.max_possible_delay_ms, 5000);
    }

    #[test]
    fn retry_config_info_serializes() {
        let info = RetryConfig::default().info();
        let json = serde_json::to_string(&info).unwrap();
        assert!(json.contains("\"max_retries\":3"));
        assert!(json.contains("\"jitter_enabled\":true"));
    }

    // ─── Response Type Serialization ────────────────────────────────────────

    #[test]
    fn usage_response_deserializes() {
        let json = r#"{
            "tier": "standard",
            "tokens_used": 50000,
            "tokens_limit": 1000000,
            "cost_usd": 0.25,
            "cost_limit_usd": 10.0,
            "assignments_count": 42,
            "period": {"start": "2026-08-01", "end": "2026-09-01"}
        }"#;
        let resp: UsageResponse = serde_json::from_str(json).unwrap();
        assert_eq!(resp.tier, "standard");
        assert_eq!(resp.tokens_used, 50000);
        assert_eq!(resp.assignments_count, 42);
        assert_eq!(resp.period.start, "2026-08-01");
    }

    #[test]
    fn usage_summary_response_deserializes() {
        let json = r#"{
            "tier": "pro",
            "tokens_used": 750000,
            "tokens_limit": 2000000,
            "token_quota_pct": 37.5,
            "cost_usd": 3.75,
            "cost_limit_usd": 20.0,
            "cost_quota_pct": 18.75,
            "assignments_count": 150,
            "projected_tokens": 1500000,
            "projected_cost_usd": 7.50,
            "billing_period": {
                "start": "2026-08-01",
                "end": "2026-09-01",
                "days_remaining": 9
            },
            "sparkline": [
                {"label": "Aug 22", "tokens": 50000, "cost_usd": 0.25, "requests": 10}
            ]
        }"#;
        let resp: UsageSummaryResponse = serde_json::from_str(json).unwrap();
        assert_eq!(resp.tier, "pro");
        assert_eq!(resp.token_quota_pct, 37.5);
        assert_eq!(resp.billing_period.days_remaining, 9);
        assert_eq!(resp.sparkline.len(), 1);
    }

    #[test]
    fn rate_limit_response_deserializes() {
        let json = r#"{
            "key_label": "vr_stand...",
            "tier": "standard",
            "rate_limit": {"max_requests_per_minute": 60, "resets_in_secs": 45},
            "tokens": {"used": 50000, "limit": 1000000, "quota_pct": 5.0, "projected_monthly": 200000},
            "cost": {"used_usd": 0.25, "limit_usd": 10.0, "quota_pct": 2.5, "projected_monthly_usd": 1.0},
            "billing_period": {"start": "2026-08-01", "resets_in_days": 9}
        }"#;
        let resp: RateLimitResponse = serde_json::from_str(json).unwrap();
        assert_eq!(resp.rate_limit.max_requests_per_minute, 60);
        assert_eq!(resp.tokens.quota_pct, 5.0);
        assert_eq!(resp.cost.projected_monthly_usd, 1.0);
        assert_eq!(resp.billing_period.resets_in_days, 9);
    }

    #[test]
    fn health_response_deserializes() {
        let json = r#"{"status": "ok", "version": "1.4.0", "models_available": 12}"#;
        let resp: HealthResponse = serde_json::from_str(json).unwrap();
        assert_eq!(resp.status, "ok");
        assert_eq!(resp.version, "1.4.0");
        assert_eq!(resp.models_available, 12);
    }

    #[test]
    fn key_detail_response_deserializes() {
        let json = r#"{
            "hash": "abc123",
            "label": "vr_stand...",
            "tier": "standard",
            "created_at": "2026-01-01T00:00:00Z",
            "tokens_used": 50000,
            "cost_usd": 0.25,
            "assignments_count": 42,
            "monthly_token_limit": 1000000,
            "monthly_cost_limit_usd": 10.0
        }"#;
        let resp: KeyDetailResponse = serde_json::from_str(json).unwrap();
        assert_eq!(resp.hash, "abc123");
        assert_eq!(resp.tokens_used, 50000);
        assert_eq!(resp.monthly_cost_limit_usd, 10.0);
    }

    #[test]
    fn rotate_key_response_deserializes() {
        let json = r#"{
            "hash": "abc123",
            "new_key": "vr_standard_newkey123",
            "old_key_revoked": true
        }"#;
        let resp: RotateKeyResponse = serde_json::from_str(json).unwrap();
        assert_eq!(resp.hash, "abc123");
        assert_eq!(resp.new_key, "vr_standard_newkey123");
        assert!(resp.old_key_revoked);
    }

    #[test]
    fn assignment_request_serialization_minimal() {
        let req = AssignmentRequest {
            task: "write a function".into(),
            tier: "standard".into(),
            context: None,
            file_paths: vec![],
            max_cost_usd: None,
        };
        let json = serde_json::to_string(&req).unwrap();
        assert!(json.contains("\"task\""));
        assert!(json.contains("\"tier\""));
        // Optional fields should be skipped.
        assert!(!json.contains("\"context\""));
        assert!(!json.contains("\"file_paths\""));
        assert!(!json.contains("\"max_cost_usd\""));
    }

    #[test]
    fn assignment_request_serialization_full() {
        let req = AssignmentRequest {
            task: "refactor module".into(),
            tier: "pro".into(),
            context: Some("Rust codebase".into()),
            file_paths: vec!["src/main.rs".into(), "src/lib.rs".into()],
            max_cost_usd: Some(0.50),
        };
        let json = serde_json::to_string(&req).unwrap();
        assert!(json.contains("\"context\""));
        assert!(json.contains("\"file_paths\""));
        assert!(json.contains("\"max_cost_usd\""));
        assert!(json.contains("src/main.rs"));
    }

    #[test]
    fn assignment_response_deserializes() {
        let json = r#"{
            "id": "assign-001",
            "status": "completed",
            "created_at": "2026-08-23T10:00:00Z",
            "completed_at": "2026-08-23T10:01:00Z",
            "assembled_output": "fn main() {}",
            "cost": {"total_tokens": 5000, "total_cost_usd": 0.005},
            "error": null
        }"#;
        let resp: AssignmentResponse = serde_json::from_str(json).unwrap();
        assert_eq!(resp.id, "assign-001");
        assert_eq!(resp.status, "completed");
        assert!(resp.completed_at.is_some());
        assert_eq!(resp.cost.unwrap().total_tokens, 5000);
        assert!(resp.error.is_none());
    }

    #[test]
    fn assignment_response_error_case() {
        let json = r#"{
            "id": "assign-002",
            "status": "failed",
            "created_at": "2026-08-23T10:00:00Z",
            "completed_at": null,
            "assembled_output": null,
            "cost": null,
            "error": "model timeout"
        }"#;
        let resp: AssignmentResponse = serde_json::from_str(json).unwrap();
        assert_eq!(resp.status, "failed");
        assert!(resp.completed_at.is_none());
        assert!(resp.cost.is_none());
        assert_eq!(resp.error.unwrap(), "model timeout");
    }

    // ─── ClientDiagnostics ──────────────────────────────────────────────────

    #[test]
    fn client_diagnostics_clone() {
        let client = VelocityClient::new(VelocityConfig {
            base_url: "https://router.velocity.io".into(),
            api_key: "vr_standard_abcdef1234567890".into(),
        });
        let diag = client.diagnostics();
        let cloned = diag.clone();
        assert_eq!(cloned.connection.base_url, diag.connection.base_url);
        assert_eq!(cloned.retry.max_retries, diag.retry.max_retries);
    }

    #[test]
    fn client_diagnostics_json_roundtrip() {
        let client = VelocityClient::new(VelocityConfig {
            base_url: "https://router.velocity.io".into(),
            api_key: "vr_standard_abcdef1234567890".into(),
        });
        let diag = client.diagnostics();
        let json = serde_json::to_string(&diag).unwrap();
        let parsed: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed["connection"]["base_url"], "https://router.velocity.io");
        assert_eq!(parsed["connection"]["is_https"], true);
        assert_eq!(parsed["retry"]["max_retries"], 3);
    }

    // ─── UsageDetailed & ModelUsage ─────────────────────────────────────────

    #[test]
    fn usage_detailed_deserializes() {
        let json = r#"{
            "label": "This period",
            "tier": "standard",
            "total_assignments": 100,
            "total_tokens": 500000,
            "total_cost_usd": 2.50,
            "by_model": [
                {"model_id": "gpt-4o", "assignments": 60, "tokens": 300000, "cost_usd": 1.50},
                {"model_id": "claude-3.5-sonnet", "assignments": 40, "tokens": 200000, "cost_usd": 1.00}
            ],
            "by_domain": [
                {"domain": "gui_design", "assignments": 70, "tokens": 350000, "cost_usd": 1.75},
                {"domain": "code_gen", "assignments": 30, "tokens": 150000, "cost_usd": 0.75}
            ]
        }"#;
        let resp: UsageDetailed = serde_json::from_str(json).unwrap();
        assert_eq!(resp.total_assignments, 100);
        assert_eq!(resp.by_model.len(), 2);
        assert_eq!(resp.by_domain.len(), 2);
        assert_eq!(resp.by_model[0].model_id, "gpt-4o");
        assert_eq!(resp.by_domain[1].domain, "code_gen");
    }

    // ─── Transparency types ─────────────────────────────────────────────────

    #[test]
    fn available_model_deserializes() {
        let json = r#"{
            "id": "gpt-4o",
            "label": "GPT-4o",
            "provider": "openai",
            "tier": "pro",
            "cost_input_per_mtok": 5.0,
            "cost_output_per_mtok": 15.0
        }"#;
        let model: AvailableModel = serde_json::from_str(json).unwrap();
        assert_eq!(model.id, "gpt-4o");
        assert_eq!(model.cost_input_per_mtok, 5.0);
    }

    #[test]
    fn routing_decision_with_optional_rationale() {
        let json = r#"{
            "timestamp": "2026-08-23T12:00:00Z",
            "assignment_id": "abc-123",
            "domain": "gui_design",
            "model_id": "gpt-4o",
            "provider": "openai",
            "input_tokens": 3000,
            "output_tokens": 2000,
            "total_tokens": 5000,
            "cost_usd": 0.005,
            "duration_ms": 1500,
            "success": true,
            "routing_rationale": null
        }"#;
        let decision: RoutingDecision = serde_json::from_str(json).unwrap();
        assert!(decision.success);
        assert!(decision.routing_rationale.is_none());
    }

    #[test]
    fn routing_decision_with_rationale() {
        let json = r#"{
            "timestamp": "2026-08-23T12:00:00Z",
            "assignment_id": "abc-123",
            "domain": "gui_design",
            "model_id": "gpt-4o",
            "provider": "openai",
            "input_tokens": 3000,
            "output_tokens": 2000,
            "total_tokens": 5000,
            "cost_usd": 0.005,
            "duration_ms": 1500,
            "success": true,
            "routing_rationale": "Best for GUI tasks"
        }"#;
        let decision: RoutingDecision = serde_json::from_str(json).unwrap();
        assert_eq!(decision.routing_rationale.as_deref(), Some("Best for GUI tasks"));
    }

    // ─── dirs_next ──────────────────────────────────────────────────────────

    #[test]
    fn dirs_next_returns_some() {
        // USERPROFILE or HOME should be set in any normal environment.
        let home = dirs_next();
        assert!(home.is_some());
    }

    // ─── JSON Key Count Verification ─────────────────────────────────────────

    #[test]
    fn connection_info_json_has_exactly_5_keys() {
        let cfg = VelocityConfig {
            base_url: "https://router.velocity.io".into(),
            api_key: "vr_standard_abcdef1234567890".into(),
        };
        let info = cfg.connection_info();
        let val: serde_json::Value = serde_json::to_value(&info).unwrap();
        assert_eq!(val.as_object().unwrap().len(), 5);
        assert!(val.get("base_url").is_some());
        assert!(val.get("api_key_prefix").is_some());
        assert!(val.get("api_key_length").is_some());
        assert!(val.get("is_https").is_some());
        assert!(val.get("validation_issues").is_some());
    }

    #[test]
    fn retry_config_info_json_has_exactly_6_keys() {
        let info = RetryConfig::default().info();
        let val: serde_json::Value = serde_json::to_value(&info).unwrap();
        assert_eq!(val.as_object().unwrap().len(), 6);
        assert!(val.get("max_retries").is_some());
        assert!(val.get("initial_backoff_ms").is_some());
        assert!(val.get("max_backoff_ms").is_some());
        assert!(val.get("jitter_enabled").is_some());
        assert!(val.get("max_possible_delay_ms").is_some());
        assert!(val.get("validation_issues").is_some());
    }

    #[test]
    fn client_diagnostics_json_has_exactly_2_keys() {
        let client = VelocityClient::new(VelocityConfig {
            base_url: "http://localhost:8787".into(),
            api_key: "vr_test_key_12345".into(),
        });
        let diag = client.diagnostics();
        let val: serde_json::Value = serde_json::to_value(&diag).unwrap();
        assert_eq!(val.as_object().unwrap().len(), 2);
        assert!(val.get("connection").is_some());
        assert!(val.get("retry").is_some());
    }

    #[test]
    fn health_response_json_has_exactly_3_keys() {
        let json = r#"{"status": "ok", "version": "1.4.0", "models_available": 12}"#;
        let resp: HealthResponse = serde_json::from_str(json).unwrap();
        let val: serde_json::Value = serde_json::to_value(&resp).unwrap();
        assert_eq!(val.as_object().unwrap().len(), 3);
    }

    #[test]
    fn usage_response_json_has_exactly_7_keys() {
        let json = r#"{
            "tier": "standard",
            "tokens_used": 50000,
            "tokens_limit": 1000000,
            "cost_usd": 0.25,
            "cost_limit_usd": 10.0,
            "assignments_count": 42,
            "period": {"start": "2026-08-01", "end": "2026-09-01"}
        }"#;
        let resp: UsageResponse = serde_json::from_str(json).unwrap();
        let val: serde_json::Value = serde_json::to_value(&resp).unwrap();
        assert_eq!(val.as_object().unwrap().len(), 7);
    }

    // ─── Clone & Debug ──────────────────────────────────────────────────────

    #[test]
    fn velocity_config_clone_independence() {
        let original = VelocityConfig {
            base_url: "https://router.velocity.io".into(),
            api_key: "vr_standard_abcdef1234567890".into(),
        };
        let mut cloned = original.clone();
        cloned.base_url = "http://localhost:9999".into();
        cloned.api_key = "changed".into();
        assert_eq!(original.base_url, "https://router.velocity.io");
        assert_eq!(original.api_key, "vr_standard_abcdef1234567890");
    }

    #[test]
    fn velocity_config_debug_format() {
        let cfg = VelocityConfig {
            base_url: "http://localhost:8787".into(),
            api_key: "secret_key".into(),
        };
        let debug = format!("{:?}", cfg);
        assert!(debug.contains("VelocityConfig"));
        assert!(debug.contains("localhost"));
    }

    #[test]
    fn retry_config_clone_independence() {
        let original = RetryConfig::default();
        let mut cloned = original.clone();
        cloned.max_retries = 99;
        cloned.jitter = false;
        assert_eq!(original.max_retries, 3);
        assert!(original.jitter);
        assert_eq!(cloned.max_retries, 99);
        assert!(!cloned.jitter);
    }

    #[test]
    fn retry_config_debug_format() {
        let cfg = RetryConfig::default();
        let debug = format!("{:?}", cfg);
        assert!(debug.contains("RetryConfig"));
        assert!(debug.contains("max_retries"));
    }

    // ─── parse_toml Additional ───────────────────────────────────────────────

    #[test]
    fn parse_toml_duplicate_keys_last_wins() {
        let content = r#"
base_url = "http://first:8787"
base_url = "http://second:8787"
"#;
        let parsed = parse_toml_simple(content);
        assert_eq!(parsed.get("base_url").unwrap(), "http://second:8787");
    }

    #[test]
    fn parse_toml_whitespace_in_values() {
        let content = r#"  base_url = "http://localhost:8787"  "#;
        let parsed = parse_toml_simple(content);
        assert_eq!(parsed.get("base_url").unwrap(), "http://localhost:8787");
    }

    #[test]
    fn parse_toml_multiple_keys() {
        let content = r#"
base_url = "http://localhost:8787"
api_key = "vr_test_123"
extra_key = "extra_value"
"#;
        let parsed = parse_toml_simple(content);
        assert_eq!(parsed.len(), 3);
        assert_eq!(parsed.get("extra_key").unwrap(), "extra_value");
    }

    // ─── fmt Additional Edge Cases ──────────────────────────────────────────

    #[test]
    fn fmt_number_max_u64() {
        let result = fmt_number(u64::MAX);
        assert_eq!(result, "18,446,744,073,709,551,615");
    }

    #[test]
    fn fmt_currency_negative_amount() {
        // Negative amounts are < 0.01 so they use 4-decimal format.
        let result = fmt_currency(-1.50);
        assert_eq!(result, "$-1.5000");
    }

    #[test]
    fn fmt_percent_large_values() {
        assert_eq!(fmt_percent(1000.0), "1000.0%");
        assert_eq!(fmt_percent(999.99), "1000.0%");
    }

    // ─── Sub-type Deserialization ────────────────────────────────────────────

    #[test]
    fn usage_period_deserializes() {
        let json = r#"{"start": "2026-01-01", "end": "2026-02-01"}"#;
        let period: UsagePeriod = serde_json::from_str(json).unwrap();
        assert_eq!(period.start, "2026-01-01");
        assert_eq!(period.end, "2026-02-01");
    }

    #[test]
    fn model_usage_deserializes() {
        let json = r#"{"model_id": "gpt-4o", "assignments": 60, "tokens": 300000, "cost_usd": 1.50}"#;
        let usage: ModelUsage = serde_json::from_str(json).unwrap();
        assert_eq!(usage.model_id, "gpt-4o");
        assert_eq!(usage.assignments, 60);
        assert_eq!(usage.tokens, 300000);
    }

    #[test]
    fn domain_usage_deserializes() {
        let json = r#"{"domain": "gui_design", "assignments": 70, "tokens": 350000, "cost_usd": 1.75}"#;
        let usage: DomainUsage = serde_json::from_str(json).unwrap();
        assert_eq!(usage.domain, "gui_design");
        assert_eq!(usage.assignments, 70);
    }

    #[test]
    fn assignment_cost_deserializes() {
        let json = r#"{"total_tokens": 5000, "total_cost_usd": 0.005}"#;
        let cost: AssignmentCost = serde_json::from_str(json).unwrap();
        assert_eq!(cost.total_tokens, 5000);
        assert_eq!(cost.total_cost_usd, 0.005);
    }

    #[test]
    fn latency_percentiles_field_values() {
        let json = r#"{"p50_ms": 100, "p90_ms": 500, "p95_ms": 800, "p99_ms": 2000}"#;
        let p: LatencyPercentiles = serde_json::from_str(json).unwrap();
        assert_eq!(p.p50_ms, 100);
        assert_eq!(p.p90_ms, 500);
        assert_eq!(p.p95_ms, 800);
        assert_eq!(p.p99_ms, 2000);
    }

    #[test]
    fn model_latency_deserializes() {
        let json = r#"{"model_id": "claude-3", "p50_ms": 50, "p90_ms": 200, "p95_ms": 400, "p99_ms": 1000, "request_count": 500}"#;
        let ml: ModelLatency = serde_json::from_str(json).unwrap();
        assert_eq!(ml.model_id, "claude-3");
        assert_eq!(ml.request_count, 500);
    }

    #[test]
    fn audit_model_breakdown_optional_domain() {
        let json = r#"{
            "model_id": "gpt-4o",
            "provider": "openai",
            "domain": null,
            "tokens_used": 1000,
            "input_tokens": 600,
            "output_tokens": 400,
            "cost_usd": 0.01,
            "duration_ms": 500,
            "success": true,
            "routing_rationale": null
        }"#;
        let bd: AuditModelBreakdown = serde_json::from_str(json).unwrap();
        assert!(bd.domain.is_none());
        assert!(bd.routing_rationale.is_none());
        assert_eq!(bd.tokens_used, 1000);
    }

    #[test]
    fn billing_period_detail_deserializes() {
        let json = r#"{"start": "2026-08-01", "end": "2026-09-01", "days_remaining": 15}"#;
        let bp: BillingPeriodDetail = serde_json::from_str(json).unwrap();
        assert_eq!(bp.days_remaining, 15);
        assert_eq!(bp.end, "2026-09-01");
    }

    // ─── Retry Config Edge Cases ────────────────────────────────────────────

    #[test]
    fn retry_config_info_all_issues_combined() {
        let cfg = RetryConfig {
            max_retries: 0,
            initial_backoff_ms: 0,
            max_backoff_ms: 0,
            jitter: false,
        };
        let info = cfg.info();
        // max_retries=0 → issue, initial_backoff=0 → issue, max_backoff(0) < initial(0) → no (equal).
        assert!(info.validation_issues.len() >= 2);
        assert_eq!(info.max_possible_delay_ms, 0);
    }

    #[test]
    fn retry_config_info_high_retry_exponent() {
        // max_retries=20 → 100 * 2^20 = 104_857_600, capped at max=5000 → 5000.
        let cfg = RetryConfig {
            max_retries: 20,
            initial_backoff_ms: 100,
            max_backoff_ms: 5000,
            jitter: false,
        };
        let info = cfg.info();
        assert_eq!(info.max_possible_delay_ms, 5000);
    }

    // ─── URL Builder Additional ──────────────────────────────────────────────

    #[test]
    fn url_builder_multiple_trailing_slashes() {
        let client = VelocityClient::new(VelocityConfig {
            base_url: "http://localhost:8787///".into(),
            api_key: "test".into(),
        });
        // trim_end_matches('/') removes all trailing slashes.
        assert_eq!(client.url("/health"), "http://localhost:8787/health");
    }

    #[test]
    fn auth_header_with_special_chars() {
        let client = VelocityClient::new(VelocityConfig {
            base_url: "http://localhost:8787".into(),
            api_key: "vr_key-with-special!chars@123".into(),
        });
        assert_eq!(client.auth_header(), "Bearer vr_key-with-special!chars@123");
    }

    // ─── Phase L: New Response Type Tests ─────────────────────────────────

    #[test]
    fn recent_assignments_response_deserializes() {
        let json = r#"{
            "assignments": [
                {
                    "id": "a123",
                    "status": "Completed",
                    "created_at": "2026-08-24T10:00:00Z",
                    "completed_at": "2026-08-24T10:01:00Z",
                    "cost_usd": 0.05,
                    "total_tokens": 1500,
                    "subtask_count": 3,
                    "error": null
                }
            ],
            "total": 1
        }"#;
        let resp: RecentAssignmentsResponse = serde_json::from_str(json).unwrap();
        assert_eq!(resp.total, 1);
        assert_eq!(resp.assignments.len(), 1);
        assert_eq!(resp.assignments[0].id, "a123");
        assert_eq!(resp.assignments[0].status, "Completed");
        assert_eq!(resp.assignments[0].total_tokens, Some(1500));
        assert!(resp.assignments[0].error.is_none());
    }

    #[test]
    fn webhook_stats_response_deserializes() {
        let json = r#"{
            "webhooks": [
                {
                    "webhook_id": "wh_123",
                    "delivered": 10,
                    "failed": 2,
                    "last_delivery": "2026-08-24T12:00:00Z",
                    "last_failure": "2026-08-24T11:00:00Z"
                }
            ],
            "summary": {
                "total_webhooks": 1,
                "total_delivered": 10,
                "total_failed": 2
            }
        }"#;
        let resp: WebhookStatsResponse = serde_json::from_str(json).unwrap();
        assert_eq!(resp.summary.total_webhooks, 1);
        assert_eq!(resp.summary.total_delivered, 10);
        assert_eq!(resp.summary.total_failed, 2);
        assert_eq!(resp.webhooks[0].delivered, 10);
        assert_eq!(resp.webhooks[0].failed, 2);
    }

    #[test]
    fn rate_limits_response_deserializes() {
        let json = r#"{
            "tiers": {
                "lite": {
                    "requests_per_minute": 10,
                    "monthly_tokens": 500000,
                    "monthly_cost_usd": 5.0,
                    "description": "Free tier"
                }
            },
            "headers": {
                "X-RateLimit-Limit": "Max requests per window"
            },
            "webhook_events": ["assignment.completed"]
        }"#;
        let resp: RateLimitsResponse = serde_json::from_str(json).unwrap();
        assert_eq!(resp.tiers.len(), 1);
        assert_eq!(resp.tiers["lite"].requests_per_minute, 10);
        assert_eq!(resp.webhook_events.len(), 1);
    }

    #[test]
    fn changelog_response_deserializes() {
        let json = r#"{
            "versions": [
                {
                    "version": "0.5.0",
                    "date": "2026-08-24",
                    "changes": ["New endpoint", "Bug fix"]
                }
            ]
        }"#;
        let resp: ChangelogResponse = serde_json::from_str(json).unwrap();
        assert_eq!(resp.versions.len(), 1);
        assert_eq!(resp.versions[0].version, "0.5.0");
        assert_eq!(resp.versions[0].changes.len(), 2);
    }

    #[test]
    fn models_response_deserializes() {
        let json = r#"{
            "models": [
                {
                    "id": "deepseek-v3",
                    "label": "DeepSeek V3",
                    "provider": "deepseek",
                    "tier": "standard",
                    "cost_input_per_mtok": 0.27,
                    "cost_output_per_mtok": 1.10,
                    "domains": ["code_generation", "backend"]
                }
            ],
            "total": 1
        }"#;
        let resp: ModelsResponse = serde_json::from_str(json).unwrap();
        assert_eq!(resp.total, 1);
        assert_eq!(resp.models[0].id, "deepseek-v3");
        assert_eq!(resp.models[0].domains.len(), 2);
    }

    #[test]
    fn batch_response_deserializes() {
        let json = r#"{
            "results": [
                {
                    "index": 0,
                    "assignment_id": "abc123",
                    "status": "completed",
                    "subtask_count": 2,
                    "tokens_used": 1500,
                    "cost_usd": 0.005,
                    "results": []
                }
            ],
            "total_tasks": 1,
            "total_tokens": 1500,
            "total_cost_usd": 0.005
        }"#;
        let resp: BatchResponse = serde_json::from_str(json).unwrap();
        assert_eq!(resp.total_tasks, 1);
        assert_eq!(resp.results[0].assignment_id, "abc123");
        assert_eq!(resp.results[0].status, "completed");
    }

    #[test]
    fn echo_response_deserializes() {
        let json = r#"{
            "status": "ok",
            "authorization": "Bearer vr_stan...abcd",
            "headers": {"x-request-id": "123"}
        }"#;
        let resp: EchoResponse = serde_json::from_str(json).unwrap();
        assert_eq!(resp.status, "ok");
        assert!(resp.authorization.contains("Bearer"));
    }

    #[test]
    fn analytics_response_deserializes() {
        let json = r#"{
            "total_assignments": 42,
            "total_tokens": 100000,
            "total_cost_usd": 0.50,
            "success_rate": 0.95,
            "avg_duration_ms": 1200.0
        }"#;
        let resp: AnalyticsResponse = serde_json::from_str(json).unwrap();
        assert_eq!(resp.total_assignments, 42);
        assert!((resp.success_rate - 0.95).abs() < 0.001);
    }

    #[test]
    fn provider_health_response_deserializes() {
        let json = r#"{
            "providers": [
                {
                    "provider": "anthropic",
                    "state": "closed",
                    "consecutive_failures": 0,
                    "consecutive_successes": 5
                }
            ]
        }"#;
        let resp: ProviderHealthResponse = serde_json::from_str(json).unwrap();
        assert_eq!(resp.providers.len(), 1);
        assert_eq!(resp.providers[0].provider, "anthropic");
        assert_eq!(resp.providers[0].state, "closed");
    }
}
