//! Velocity Router HTTP client.
//!
//! Provides a typed interface to the Velocity Model Router API for usage
//! tracking, assignment submission, cost monitoring, transparency data,
//! timeseries analytics, audit logs, and API key management.

use std::collections::HashMap;
use std::time::Duration;

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

/// Configuration for connecting to the Velocity Router.
#[derive(Debug, Clone)]
pub struct VelocityConfig {
    pub base_url: String,
    pub api_key: String,
}

impl VelocityConfig {
    /// Load from environment variables or config file.
    /// Checks VELOCITY_BASE_URL and VELOCITY_API_KEY env vars first,
    /// then falls back to ~/.velocity/config.toml.
    pub fn load() -> Result<Self> {
        // Try environment variables first.
        if let (Ok(url), Ok(key)) = (
            std::env::var("VELOCITY_BASE_URL"),
            std::env::var("VELOCITY_API_KEY"),
        ) {
            return Ok(Self {
                base_url: url,
                api_key: key,
            });
        }

        // Try ~/.velocity/config.toml with proper TOML parsing.
        if let Some(home) = dirs_next() {
            let config_path = home.join(".velocity").join("config.toml");
            if config_path.exists() {
                let content = std::fs::read_to_string(&config_path)
                    .context("failed to read ~/.velocity/config.toml")?;
                let parsed = parse_toml_simple(&content);
                if let (Some(url), Some(key)) = (
                    parsed.get("base_url").cloned(),
                    parsed.get("api_key").cloned(),
                ) {
                    return Ok(Self {
                        base_url: url,
                        api_key: key,
                    });
                }
            }
        }

        anyhow::bail!(
            "Velocity Router not configured.\n\
             Set VELOCITY_BASE_URL and VELOCITY_API_KEY environment variables,\n\
             or create ~/.velocity/config.toml with:\n\
             \n\
             base_url = \"http://localhost:8787\"\n\
             api_key = \"vr_standard_your_key_here\""
        )
    }

    /// Save configuration to ~/.velocity/config.toml.
    pub fn save(&self) -> Result<()> {
        if let Some(home) = dirs_next() {
            let config_dir = home.join(".velocity");
            std::fs::create_dir_all(&config_dir)
                .context("failed to create ~/.velocity directory")?;
            let config_path = config_dir.join("config.toml");
            let content = format!(
                "# Velocity Router configuration\n\
                 # Generated by velocity-ide login\n\
                 \n\
                 base_url = \"{}\"\n\
                 api_key = \"{}\"\n",
                self.base_url, self.api_key
            );
            std::fs::write(&config_path, content)
                .context("failed to write ~/.velocity/config.toml")?;
            Ok(())
        } else {
            anyhow::bail!("cannot determine home directory")
        }
    }
}

/// Minimal TOML key-value parser (handles simple `key = "value"` lines).
/// Skips comments, blank lines, section headers, and lines within sections.
/// Avoids pulling in the `toml` crate for this single use case.
fn parse_toml_simple(content: &str) -> HashMap<String, String> {
    let mut map = HashMap::new();
    let mut in_section = false;
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        // Section header — stop parsing top-level keys until next blank line.
        if line.starts_with('[') {
            in_section = true;
            continue;
        }
        // A new top-level key resets section tracking.
        if in_section {
            // Lines within a section are skipped.
            continue;
        }
        if let Some((key, value)) = line.split_once('=') {
            let key = key.trim().to_string();
            let value = value.trim().trim_matches('"').to_string();
            map.insert(key, value);
        }
    }
    map
}

/// Simple home directory lookup without adding a dependency.
fn dirs_next() -> Option<std::path::PathBuf> {
    std::env::var_os("USERPROFILE")
        .or_else(|| std::env::var_os("HOME"))
        .map(std::path::PathBuf::from)
}

// ─── API Response Types ─────────────────────────────────────────────────

#[derive(Debug, Serialize, Deserialize)]
pub struct UsageResponse {
    pub tier: String,
    pub tokens_used: u64,
    pub tokens_limit: u64,
    pub cost_usd: f64,
    pub cost_limit_usd: f64,
    pub assignments_count: u64,
    pub period: UsagePeriod,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct UsagePeriod {
    pub start: String,
    pub end: String,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct UsageDetailed {
    pub label: String,
    pub tier: String,
    pub total_assignments: u64,
    pub total_tokens: u64,
    pub total_cost_usd: f64,
    pub by_model: Vec<ModelUsage>,
    pub by_domain: Vec<DomainUsage>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct ModelUsage {
    pub model_id: String,
    pub assignments: u64,
    pub tokens: u64,
    pub cost_usd: f64,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct DomainUsage {
    pub domain: String,
    pub assignments: u64,
    pub tokens: u64,
    pub cost_usd: f64,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct RateLimitResponse {
    pub key_label: String,
    pub tier: String,
    pub rate_limit: RateLimitInfo,
    pub tokens: QuotaInfo,
    pub cost: CostInfo,
    pub billing_period: BillingPeriodInfo,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct RateLimitInfo {
    pub max_requests_per_minute: u32,
    pub resets_in_secs: u64,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct QuotaInfo {
    pub used: u64,
    pub limit: u64,
    pub quota_pct: f64,
    pub projected_monthly: u64,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct CostInfo {
    pub used_usd: f64,
    pub limit_usd: f64,
    pub quota_pct: f64,
    pub projected_monthly_usd: f64,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct BillingPeriodInfo {
    pub start: String,
    pub resets_in_days: i64,
}

#[derive(Debug, Serialize)]
pub struct AssignmentRequest {
    pub task: String,
    pub tier: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub context: Option<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub file_paths: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_cost_usd: Option<f64>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct AssignmentResponse {
    pub id: String,
    pub status: String,
    pub created_at: String,
    pub completed_at: Option<String>,
    pub assembled_output: Option<String>,
    pub cost: Option<AssignmentCost>,
    pub error: Option<String>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct AssignmentCost {
    pub total_tokens: u64,
    pub total_cost_usd: f64,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct HealthResponse {
    pub status: String,
    pub version: String,
    pub models_available: usize,
}

// ─── Transparency Types ──────────────────────────────────────────────────

/// Response from GET /v1/transparency — full routing transparency.
#[derive(Debug, Serialize, Deserialize)]
pub struct TransparencyResponse {
    pub summary: TransparencySummary,
    pub cost_flow: CostFlow,
    pub recent_routing_decisions: Vec<RoutingDecision>,
    pub model_selection_stats: Vec<ModelSelectionStat>,
    pub domain_distribution: Vec<DomainDistribution>,
    pub available_models: Vec<AvailableModel>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct TransparencySummary {
    pub total_assignments: usize,
    pub total_errors: usize,
    pub total_input_tokens: u64,
    pub total_output_tokens: u64,
    pub total_tokens: u64,
    pub total_cost_usd: f64,
    pub models_available: usize,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct CostFlow {
    pub input_tokens: u64,
    pub output_tokens: u64,
    pub input_output_ratio: f64,
    pub total_cost_usd: f64,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct RoutingDecision {
    pub timestamp: String,
    pub assignment_id: String,
    pub domain: String,
    pub model_id: String,
    pub provider: String,
    pub input_tokens: u64,
    pub output_tokens: u64,
    pub total_tokens: u64,
    pub cost_usd: f64,
    pub duration_ms: u64,
    pub success: bool,
    pub routing_rationale: Option<String>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct ModelSelectionStat {
    pub model_id: String,
    pub total_requests: u64,
    pub total_tokens: u64,
    pub total_cost_usd: f64,
    pub avg_duration_ms: u64,
    pub domains_served: HashMap<String, u64>,
    pub top_domain: Option<String>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct DomainDistribution {
    pub domain: String,
    pub requests: u64,
    pub tokens: u64,
    pub cost_usd: f64,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct AvailableModel {
    pub id: String,
    pub label: String,
    pub provider: String,
    pub tier: String,
    pub cost_input_per_mtok: f64,
    pub cost_output_per_mtok: f64,
}

// ─── TIMESERIES TYPES ────────────────────────────────────────────────────

/// Response from GET /v1/usage/timeseries.
#[derive(Debug, Serialize, Deserialize)]
pub struct TimeseriesResponse {
    pub granularity: String,
    pub range: String,
    pub buckets: Vec<TimeseriesBucket>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct TimeseriesBucket {
    pub label: String,
    pub tokens: u64,
    pub cost_usd: f64,
    pub requests: u64,
}

// ─── USAGE SUMMARY (ENHANCED) ────────────────────────────────────────────

/// Response from GET /v1/usage/summary — enhanced usage with projections.
#[derive(Debug, Serialize, Deserialize)]
pub struct UsageSummaryResponse {
    pub tier: String,
    pub tokens_used: u64,
    pub tokens_limit: u64,
    pub token_quota_pct: f64,
    pub cost_usd: f64,
    pub cost_limit_usd: f64,
    pub cost_quota_pct: f64,
    pub assignments_count: u64,
    pub projected_tokens: u64,
    pub projected_cost_usd: f64,
    pub billing_period: BillingPeriodDetail,
    pub sparkline: Vec<TimeseriesBucket>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct BillingPeriodDetail {
    pub start: String,
    pub end: String,
    pub days_remaining: i64,
}

// ─── AUDIT LOG ───────────────────────────────────────────────────────────

/// Response from GET /v1/audit-log.
#[derive(Debug, Serialize, Deserialize)]
pub struct AuditLogResponse {
    pub total: usize,
    pub entries: Vec<AuditLogEntry>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct AuditLogEntry {
    pub timestamp: String,
    pub assignment_id: String,
    pub status: String,
    pub total_tokens: u64,
    pub total_cost_usd: f64,
    pub duration_ms: u64,
    pub model_breakdown: Vec<AuditModelBreakdown>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct AuditModelBreakdown {
    pub model_id: String,
    pub provider: String,
    pub domain: Option<String>,
    pub tokens_used: u64,
    pub input_tokens: u64,
    pub output_tokens: u64,
    pub cost_usd: f64,
    pub duration_ms: u64,
    pub success: bool,
    pub routing_rationale: Option<String>,
}

// ─── ANALYTICS ───────────────────────────────────────────────────────────

/// Response from GET /v1/analytics/latency.
#[derive(Debug, Serialize, Deserialize)]
pub struct LatencyResponse {
    pub overall: LatencyPercentiles,
    pub by_model: Vec<ModelLatency>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct LatencyPercentiles {
    pub p50_ms: u64,
    pub p90_ms: u64,
    pub p95_ms: u64,
    pub p99_ms: u64,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct ModelLatency {
    pub model_id: String,
    pub p50_ms: u64,
    pub p90_ms: u64,
    pub p95_ms: u64,
    pub p99_ms: u64,
    pub request_count: u64,
}

// ─── KEY MANAGEMENT ──────────────────────────────────────────────────────

/// Response from GET /admin/keys/:hash.
#[derive(Debug, Serialize, Deserialize)]
pub struct KeyDetailResponse {
    pub hash: String,
    pub label: String,
    pub tier: String,
    pub created_at: String,
    pub tokens_used: u64,
    pub cost_usd: f64,
    pub assignments_count: u64,
    pub monthly_token_limit: u64,
    pub monthly_cost_limit_usd: f64,
}

/// Response from POST /admin/keys/:hash/rotate.
#[derive(Debug, Serialize, Deserialize)]
pub struct RotateKeyResponse {
    pub hash: String,
    pub new_key: String,
    pub old_key_revoked: bool,
}

// ─── Client ─────────────────────────────────────────────────────────────

/// Synchronous HTTP client for the Velocity Router API.
pub struct VelocityClient {
    config: VelocityConfig,
    agent: ureq::Agent,
    retry_config: RetryConfig,
}

/// Retry configuration for HTTP requests.
#[derive(Debug, Clone)]
pub struct RetryConfig {
    /// Maximum number of retry attempts (not counting the initial request).
    pub max_retries: u32,
    /// Initial backoff duration.
    pub initial_backoff_ms: u64,
    /// Maximum backoff duration.
    pub max_backoff_ms: u64,
    /// Whether to add random jitter to backoff (avoids thundering herd).
    pub jitter: bool,
}

impl Default for RetryConfig {
    fn default() -> Self {
        Self {
            max_retries: 3,
            initial_backoff_ms: 200,
            max_backoff_ms: 5000,
            jitter: true,
        }
    }
}

impl VelocityClient {
    pub fn new(config: VelocityConfig) -> Self {
        let agent = ureq::AgentBuilder::new()
            .timeout_connect(Duration::from_secs(5))
            .timeout_read(Duration::from_secs(30))
            .timeout_write(Duration::from_secs(10))
            .build();
        Self {
            config,
            agent,
            retry_config: RetryConfig::default(),
        }
    }

    pub fn from_env() -> Result<Self> {
        let config = VelocityConfig::load()?;
        Ok(Self::new(config))
    }

    /// Set custom retry configuration.
    pub fn with_retry_config(mut self, config: RetryConfig) -> Self {
        self.retry_config = config;
        self
    }

    fn auth_header(&self) -> String {
        format!("Bearer {}", self.config.api_key)
    }

    fn url(&self, path: &str) -> String {
        format!("{}{}", self.config.base_url.trim_end_matches('/'), path)
    }

    /// Compute backoff duration with optional jitter.
    fn backoff_duration(&self, base_ms: u64) -> Duration {
        let ms = if self.retry_config.jitter {
            // Add ±25% random jitter to avoid thundering herd.
            let jitter_range = base_ms / 4;
            let jitter = if jitter_range > 0 {
                (rand::random::<u64>() % (jitter_range * 2)).saturating_sub(jitter_range)
            } else {
                0
            };
            base_ms.saturating_add_signed(jitter as i64)
        } else {
            base_ms
        };
        Duration::from_millis(ms.min(self.retry_config.max_backoff_ms))
    }

    /// Execute a GET request with exponential backoff retry.
    /// Retries on 5xx errors and transport failures.
    fn get_with_retry(&self, url: &str, auth: bool) -> Result<ureq::Response> {
        let mut last_error = None;
        let mut backoff = self.retry_config.initial_backoff_ms;

        for attempt in 0..=self.retry_config.max_retries {
            let mut req = self.agent.get(url);
            if auth {
                req = req.set("Authorization", &self.auth_header());
            }

            match req.call() {
                Ok(resp) => return Ok(resp),
                Err(ureq::Error::Status(code, _resp)) if code >= 500 => {
                    last_error = Some(anyhow::anyhow!("server error: HTTP {}", code));
                    if attempt < self.retry_config.max_retries {
                        std::thread::sleep(self.backoff_duration(backoff));
                        backoff = (backoff * 2).min(self.retry_config.max_backoff_ms);
                    }
                }
                Err(ureq::Error::Transport(_)) => {
                    last_error = Some(anyhow::anyhow!("transport error (connection failed)"));
                    if attempt < self.retry_config.max_retries {
                        std::thread::sleep(self.backoff_duration(backoff));
                        backoff = (backoff * 2).min(self.retry_config.max_backoff_ms);
                    }
                }
                Err(e) => return Err(anyhow::anyhow!("{}", e)),
            }
        }

        Err(last_error.unwrap_or_else(|| anyhow::anyhow!("max retries exceeded")))
    }

    /// GET /health — check if the router is reachable.
    pub fn health(&self) -> Result<HealthResponse> {
        let resp = self
            .get_with_retry(&self.url("/health"), false)
            .context("failed to reach velocity router")?;
        resp.into_json()
            .context("failed to parse health response")
    }

    /// GET /v1/usage — current usage summary.
    pub fn get_usage(&self) -> Result<UsageResponse> {
        let resp = self
            .get_with_retry(&self.url("/v1/usage"), true)
            .context("failed to fetch usage")?;
        resp.into_json()
            .context("failed to parse usage response")
    }

    /// GET /v1/usage/summary — enhanced usage with projections and sparkline.
    pub fn get_usage_summary(&self) -> Result<UsageSummaryResponse> {
        let resp = self
            .get_with_retry(&self.url("/v1/usage/summary"), true)
            .context("failed to fetch usage summary")?;
        resp.into_json()
            .context("failed to parse usage summary response")
    }

    /// GET /v1/usage/detailed — per-model and per-domain breakdown.
    pub fn get_usage_detailed(&self) -> Result<UsageDetailed> {
        let resp = self
            .get_with_retry(&self.url("/v1/usage/detailed"), true)
            .context("failed to fetch detailed usage")?;
        resp.into_json()
            .context("failed to parse detailed usage response")
    }

    /// GET /v1/usage/rate-limit — rate limit and quota status.
    pub fn get_rate_limit(&self) -> Result<RateLimitResponse> {
        let resp = self
            .get_with_retry(&self.url("/v1/usage/rate-limit"), true)
            .context("failed to fetch rate limit status")?;
        resp.into_json()
            .context("failed to parse rate limit response")
    }

    /// GET /v1/usage/timeseries — time-series usage data.
    /// `granularity`: "hourly" or "daily".
    /// `range`: "6h", "12h", "24h", "48h", "7d", "30d", "90d".
    pub fn get_timeseries(&self, granularity: &str, range: &str) -> Result<TimeseriesResponse> {
        let url = format!(
            "{}/v1/usage/timeseries?granularity={}&range={}",
            self.config.base_url.trim_end_matches('/'),
            granularity,
            range
        );
        let resp = self
            .get_with_retry(&url, true)
            .context("failed to fetch timeseries")?;
        resp.into_json()
            .context("failed to parse timeseries response")
    }

    /// GET /v1/transparency — full routing transparency data.
    pub fn get_transparency(&self) -> Result<TransparencyResponse> {
        let resp = self
            .get_with_retry(&self.url("/v1/transparency"), true)
            .context("failed to fetch transparency data")?;
        resp.into_json()
            .context("failed to parse transparency response")
    }

    /// GET /v1/audit-log — paginated audit trail.
    pub fn get_audit_log(&self) -> Result<AuditLogResponse> {
        let resp = self
            .get_with_retry(&self.url("/v1/audit-log"), true)
            .context("failed to fetch audit log")?;
        resp.into_json()
            .context("failed to parse audit log response")
    }

    /// GET /v1/analytics/latency — latency percentiles.
    pub fn get_latency(&self) -> Result<LatencyResponse> {
        let resp = self
            .get_with_retry(&self.url("/v1/analytics/latency"), true)
            .context("failed to fetch latency analytics")?;
        resp.into_json()
            .context("failed to parse latency response")
    }

    /// GET /admin/keys/:hash — key detail (admin only).
    pub fn get_key_detail(&self, hash: &str) -> Result<KeyDetailResponse> {
        let resp = self
            .get_with_retry(&self.url(&format!("/admin/keys/{}", hash)), true)
            .context("failed to fetch key detail")?;
        resp.into_json()
            .context("failed to parse key detail response")
    }

    /// POST /admin/keys/:hash/rotate — rotate an API key (admin only).
    pub fn rotate_key(&self, hash: &str) -> Result<RotateKeyResponse> {
        let resp = self
            .agent
            .post(&self.url(&format!("/admin/keys/{}/rotate", hash)))
            .set("Authorization", &self.auth_header())
            .call()
            .context("failed to rotate key")?;
        resp.into_json()
            .context("failed to parse rotate key response")
    }

    /// POST /v1/assignments — submit a task for orchestration.
    pub fn submit_assignment(&self, req: &AssignmentRequest) -> Result<AssignmentResponse> {
        let resp = self
            .agent
            .post(&self.url("/v1/assignments"))
            .set("Authorization", &self.auth_header())
            .set("Content-Type", "application/json")
            .send_json(serde_json::to_value(req)?)
            .context("failed to submit assignment")?;
        resp.into_json()
            .context("failed to parse assignment response")
    }

    /// GET /v1/assignments/:id — poll assignment status.
    pub fn get_assignment(&self, id: &str) -> Result<AssignmentResponse> {
        let resp = self
            .get_with_retry(&self.url(&format!("/v1/assignments/{}", id)), true)
            .context("failed to fetch assignment")?;
        resp.into_json()
            .context("failed to parse assignment response")
    }
}

// ─── Formatting Helpers ─────────────────────────────────────────────────

/// Format a number with thousands separators.
pub fn fmt_number(n: u64) -> String {
    let s = n.to_string();
    let mut result = String::new();
    for (i, c) in s.chars().rev().enumerate() {
        if i > 0 && i % 3 == 0 {
            result.push(',');
        }
        result.push(c);
    }
    result.chars().rev().collect()
}

/// Format a USD amount.
pub fn fmt_currency(n: f64) -> String {
    if n == 0.0 {
        "$0.00".to_string()
    } else if n < 0.01 {
        format!("${:.4}", n)
    } else {
        format!("${:.2}", n)
    }
}

/// Format a percentage.
pub fn fmt_percent(n: f64) -> String {
    format!("{:.1}%", n)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fmt_number_works() {
        assert_eq!(fmt_number(0), "0");
        assert_eq!(fmt_number(999), "999");
        assert_eq!(fmt_number(1000), "1,000");
        assert_eq!(fmt_number(1234567), "1,234,567");
    }

    #[test]
    fn fmt_currency_works() {
        assert_eq!(fmt_currency(0.0), "$0.00");
        assert_eq!(fmt_currency(0.0034), "$0.0034");
        assert_eq!(fmt_currency(1.5), "$1.50");
        assert_eq!(fmt_currency(123.456), "$123.46");
    }

    #[test]
    fn fmt_percent_works() {
        assert_eq!(fmt_percent(0.0), "0.0%");
        assert_eq!(fmt_percent(42.567), "42.6%");
        assert_eq!(fmt_percent(100.0), "100.0%");
    }

    #[test]
    fn config_load_from_env() {
        // Use unique prefixed env vars to avoid races with other tests.
        std::env::set_var("VELOCITY_BASE_URL", "http://test:8787");
        std::env::set_var("VELOCITY_API_KEY", "vr_test_key");
        let config = VelocityConfig::load().unwrap();
        assert_eq!(config.base_url, "http://test:8787");
        assert_eq!(config.api_key, "vr_test_key");
        // Clean up.
        std::env::remove_var("VELOCITY_BASE_URL");
        std::env::remove_var("VELOCITY_API_KEY");
        // After removing, load() should fail.
        assert!(VelocityConfig::load().is_err());
    }

    #[test]
    fn parse_toml_simple_works() {
        let content = r#"
# This is a comment
base_url = "http://localhost:8787"
api_key = "vr_standard_abc123"

[section]
ignored = true
"#;
        let parsed = parse_toml_simple(content);
        assert_eq!(parsed.get("base_url").unwrap(), "http://localhost:8787");
        assert_eq!(parsed.get("api_key").unwrap(), "vr_standard_abc123");
        // Section headers and their contents are skipped.
        assert!(parsed.get("section").is_none());
        assert!(parsed.get("ignored").is_none());
    }

    #[test]
    fn parse_toml_handles_comments_and_blanks() {
        let content = "# comment\n\nkey1 = \"val1\"\n  key2 = \"val2\"  \n";
        let parsed = parse_toml_simple(content);
        assert_eq!(parsed.get("key1").unwrap(), "val1");
        assert_eq!(parsed.get("key2").unwrap(), "val2");
    }

    #[test]
    fn retry_config_default_has_jitter() {
        let cfg = RetryConfig::default();
        assert!(cfg.jitter);
        assert_eq!(cfg.max_retries, 3);
        assert_eq!(cfg.initial_backoff_ms, 200);
        assert_eq!(cfg.max_backoff_ms, 5000);
    }

    #[test]
    fn backoff_duration_respects_max() {
        let client = VelocityClient::new(VelocityConfig {
            base_url: "http://localhost:8787".into(),
            api_key: "test".into(),
        });
        // Even with a huge base, should not exceed max_backoff_ms.
        let d = client.backoff_duration(999_999);
        assert!(d.as_millis() <= 5000);
    }

    #[test]
    fn backoff_without_jitter_is_deterministic() {
        let cfg = VelocityConfig {
            base_url: "http://localhost:8787".into(),
            api_key: "test".into(),
        };
        let client = VelocityClient::new(cfg).with_retry_config(RetryConfig {
            jitter: false,
            ..RetryConfig::default()
        });
        let d1 = client.backoff_duration(1000);
        let d2 = client.backoff_duration(1000);
        assert_eq!(d1, d2);
    }

    #[test]
    fn transparency_response_deserializes() {
        let json = r#"{
            "summary": {
                "total_assignments": 42,
                "total_errors": 1,
                "total_input_tokens": 100000,
                "total_output_tokens": 50000,
                "total_tokens": 150000,
                "total_cost_usd": 0.15,
                "models_available": 12
            },
            "cost_flow": {
                "input_tokens": 100000,
                "output_tokens": 50000,
                "input_output_ratio": 2.0,
                "total_cost_usd": 0.15
            },
            "recent_routing_decisions": [],
            "model_selection_stats": [],
            "domain_distribution": [],
            "available_models": []
        }"#;
        let resp: TransparencyResponse = serde_json::from_str(json).unwrap();
        assert_eq!(resp.summary.total_assignments, 42);
        assert_eq!(resp.cost_flow.input_output_ratio, 2.0);
        assert_eq!(resp.summary.models_available, 12);
    }

    #[test]
    fn timeseries_response_deserializes() {
        let json = r#"{
            "granularity": "hourly",
            "range": "24h",
            "buckets": [
                {"label": "14:00", "tokens": 1200, "cost_usd": 0.001, "requests": 3}
            ]
        }"#;
        let resp: TimeseriesResponse = serde_json::from_str(json).unwrap();
        assert_eq!(resp.granularity, "hourly");
        assert_eq!(resp.buckets.len(), 1);
        assert_eq!(resp.buckets[0].tokens, 1200);
    }

    #[test]
    fn audit_log_response_deserializes() {
        let json = r#"{
            "total": 1,
            "entries": [{
                "timestamp": "2026-08-23T12:00:00Z",
                "assignment_id": "abc-123",
                "status": "completed",
                "total_tokens": 5000,
                "total_cost_usd": 0.005,
                "duration_ms": 1500,
                "model_breakdown": [{
                    "model_id": "gpt-4o",
                    "provider": "openai",
                    "domain": "gui_design",
                    "tokens_used": 5000,
                    "input_tokens": 3000,
                    "output_tokens": 2000,
                    "cost_usd": 0.005,
                    "duration_ms": 1500,
                    "success": true,
                    "routing_rationale": "Best for GUI tasks"
                }]
            }]
        }"#;
        let resp: AuditLogResponse = serde_json::from_str(json).unwrap();
        assert_eq!(resp.total, 1);
        assert_eq!(resp.entries[0].model_breakdown[0].input_tokens, 3000);
        assert_eq!(resp.entries[0].model_breakdown[0].success, true);
    }

    #[test]
    fn latency_response_deserializes() {
        let json = r#"{
            "overall": {"p50_ms": 200, "p90_ms": 800, "p95_ms": 1200, "p99_ms": 3000},
            "by_model": [{
                "model_id": "gpt-4o",
                "p50_ms": 150, "p90_ms": 600, "p95_ms": 900, "p99_ms": 2500,
                "request_count": 100
            }]
        }"#;
        let resp: LatencyResponse = serde_json::from_str(json).unwrap();
        assert_eq!(resp.overall.p50_ms, 200);
        assert_eq!(resp.by_model.len(), 1);
    }
}
